/**
 * @thirdlight/project-model — public surface: types, parse*, validate*,
 * normalize*, serializeCanonical, ERROR_CODES, KNOWN_VERSIONS.
 *
 * Only storage v4 projects load (`validateProjectV4`); a v3 project is read
 * (`validateEnvelopeV3`/`validateProjectV3`) and upgraded on open
 * (`migrateProjectV3ToV4`). Shared component rules live in `components.ts`.
 * Strict byte parsing with duplicate-key rejection, total value validation,
 * normalization to the canonical form and canonical byte serialization.
 *
 * Pure data and logic: no I/O, no three.js, no Node built-ins — the leaf
 * unit of the node-side graph. All entry points are
 * pure and total: same input → same result; malformed data yields error
 * results, never thrown exceptions.
 */

export {
  ERROR_CODES,
  KNOWN_VERSIONS,
  SCHEMA_VERSIONS_BY_DOCUMENT,
  type EnvelopeV3Error,
  type EnvelopeV3ErrorCode,
  type ErrorCode,
  type LimitName,
  type ModelError,
  type ModelErrorV2,
  type ModelErrorV3,
  type ModelResult,
  type ModelResultV2,
  type ModelResultV3,
  type SerializeResult,
} from './errors';

export type {
  BoxComponent,
  BoxMaterial,
  CameraComponent,
  Manifest,
  Quat,
  SceneRef,
  TransformComponent,
  Vec3,
} from './types';

export type {
  AssetMetrics,
  AssetRecord,
  AssetVersion,
  ConvertedFrom,
  PackedChannel,
  PackedFrom,
  BehaviorComponent,
  BehaviorRecord,
  BehaviorSourceRecord,
  BehaviorTrust,
  CapturedAsset,
  CapturedContent,
  ColliderBoxShape,
  ColliderComponent,
  ColliderPolygonShape,
  ColliderSphereShape,
  ColliderCapsuleShape,
  ColliderConvexShape,
  ColliderMeshShape,
  ColliderShape,
  ColliderShapePose,
  ColliderPrimitiveShape,
  ColliderCompoundShape,
  ColliderModelShape,
  ContentCatalog,
  ControllerCapsule,
  ControllerComponent,
  DeclaredProperty,
  EntityComponentsV2,
  GameplaySettings,
  ImportRecipe,
  ModelAssetRef,
  ModelComponent,
  PrefabComponentsV2,
  PrefabDefinition,
  PrefabEntity,
  PrefabProvenanceComponent,
  PrefabComponentsV4Extra,
  PropertyBounds,
  PropertyDeclaration,
  PropertyType,
  PropertyValue,
  PropertyVisibility,
  SettingsMap,
  SettingsValue,
  TrustEntry,
} from './types-v2';

// The character capsule (default, limits, resolved form).
export { CAPSULE_LIMITS, COLLIDER_3D_LIMITS, COLLIDER_3D_SHAPES, CONTROLLER_FIELDS, CONTROLLER_TUNING_FIELDS, CONTROLLER_TUNING_LIMITS, DEFAULT_CONTROLLER_CAPSULE, DEFAULT_CONTROLLER_TUNING, controllerCapsuleOf, controllerCapsuleOffsetZ, controllerTuningOf, CHARACTER_3D_LIMITS, CONTROLLER_3D_FIELDS, DEFAULT_CHARACTER_3D, character3DSettingsOf, CHARACTER_MOVE_FRAMES, type CharacterMoveFrame, CONTROLLER_ACTION_FIELDS, CONTROLLER_ACTION_DEFAULTS, controllerActionsOf, type Character3DSettings, CONTROLLER_MOVEMENT_FIELDS, CONTROLLER_MOVEMENT_LIMITS, DEFAULT_CONTROLLER_MOVEMENT, controllerMovementOf, type ControllerMovementSettings } from './components';
// Collision layers.
export { DEFAULT_COLLISION_LAYER, MAX_COLLISION_LAYERS, validateCollisionLayers } from './components';
export { parseDocumentBytes, type ByteParse } from './parse-bytes';
export { parseEnvelopeV3, parseManifest, parseSceneV3 } from './parse-api';

export { validateManifest, normalizeManifest, boundedFound } from './validate';
export * from './limits';
export { lightLayerMaskOf, validateLightLayerMask, validateLightLayerNames } from './light-layers';
export { lightImportanceOf, localLightModeOf, validateLightImportance, validateLocalLightMode, type LightImportance, type LocalLightMode, type MaterialLocalLightMode } from './local-lights';

export {
  M2_SETTINGS_KEYS,
  NEW_PROJECT_SETTINGS,
  RENDERING_SETTINGS_GROUP,
  fixedStepHzOf,
  AUDIO_VOICE_CAP,
  PHYSICS_DIMENSIONS,
  audioSpatialOf,
  depthBufferOf,
  instanceChunkSizeOf,
  physicsDimensionOf,
  type PhysicsDimension,
  MAX_SOURCE_PATH_LENGTH,
  MAX_CONVERTED_SOURCE_BYTES,
  M2_GLTF_EXTENSION_ALLOWLIST,
  isValidSourcePath,
  normalizeContentV3,
  resolveGameplaySettings,
  validateContentV3,
  validateGameConfig,
  validateTagRegistry,
  TAG_NAME_RE,
  type SettingsKeySpec,
} from './content';

// The explicit v3 model surface: the versioned scene/content entry points,
// the v3 registry/limits/preset constants, the v3 types and the
// component-level validators.
export {
  AUDIO_DECODE_ON_LOAD_BELOW_MS,
  AUDIO_FORMATS,
  AUDIO_LOAD_TYPES,
  AUDIO_PIPELINE_NAME,
  AUDIO_PIPELINE_VERSION,
  AUDIO_STREAM_ABOVE_MS,
  audioLoadOf,
  audioPlaybackGaps,
  audioSummaryOf,
  defaultAudioLoadType,
  upgradeAudioAssets,
  upgradeAudioRecord,
  type AudioFormat,
  type AudioLoadSettings,
  type AudioLoadType,
  type AudioMetrics,
  type AudioRecipe,
  type AudioSummary,
} from './audio-assets';
export {
  TEXTURE_BUDGET_DEFAULT_MB,
  TEXTURE_BUDGET_MAX_MB,
  TEXTURE_BUDGET_MIN_MB,
  TEXTURE_STREAMING_DEFAULT_ABOVE_PX,
  TEXTURE_STREAM_TAIL_PX,
  textureBudgetBytesOf,
  textureHasStreamableChain,
  textureStreamingOf,
} from './texture-streaming';
export {
  canonicalModelLod,
  INSTANCE_DENSITY_END_DEFAULT,
  INSTANCE_DENSITY_MIN_DEFAULT,
  INSTANCE_DENSITY_MIN_NEW,
  INSTANCE_DENSITY_START_DEFAULT,
  instanceDensityOf,
  LOD_BIAS_DEFAULT,
  LOD_BIAS_MAX,
  LOD_BIAS_MIN,
  LOD_CULL_SIZE_DEFAULT,
  LOD_HYSTERESIS_DEFAULT,
  LOD_HYSTERESIS_MAX,
  LOD_REFERENCE_FOV_DEG,
  LOD_SCREEN_SIZES_DEFAULT,
  LOD_SCREEN_SIZES_MAX,
  lodCullSizeOf,
  lodScreenSizesFor,
  lodTuningOf,
  modelLodProblems,
  type InstanceDensity,
  type LodTuningSettings,
  type ModelLodSettings,
} from './model-lod';
export {
  buildKtx2Subset,
  isKtx2Bytes,
  ktx2IndexBytes,
  ktx2LevelSize,
  planKtx2Parts,
  readKtx2Layout,
  type Ktx2Layout,
  type Ktx2LayoutResult,
  type Ktx2Level,
  type Ktx2Part,
  type Ktx2Range,
} from './ktx2-levels';
export {
  normalizeSceneV3,
  validateLightComponent,
  validateModelAnimationComponent,
  validatePlayerSpawnComponent,
  validateSceneV3,
  validateSurfaceComponent,
} from './scene-v3';
export {
  SCENE_LIMITS_V3,
  SURFACE_PRESETS,
  SURFACE_PRESET_NAMES,
  type SurfacePresetName,
  V3_REGISTRY,
  isFolderEntity,
  MAX_TAGS,
  type TagDefinition,
  type EntityFlagsV3,
  type FolderComponent,
  type FolderEntityV3,
  type ResolvedSceneV3,
  type SceneEntityV3,
  type AnimationRoleBinding,
  type AssetKind,
  type AssetMetricsV3,
  type AssetRecordV3,
  type AssetVersionV3,
  type AuthoringEnvelopeV3,
  type ComponentV3,
  type ContentCatalogV3,
  type EntityComponentsV3,
  type EntityV3,
  type GltfGlbRecipeV3,
  type ImportRecipeV3,
  type LightComponent,
  type ModelAnimationComponent,
  type PlayerSpawnComponent,
  type SceneV3,
  type SurfaceComponent,
} from './types-v3';
export {
  effectiveEntityFlags,
  nearestObjectAncestor,
  resolveSceneHierarchy,
  type EffectiveEntityFlags,
} from './hierarchy-v3';
export {
  normalizeEnvelopeV3,
  validateEnvelopeV3,
  validateProjectV3,
  composeContentChecks,
  type EnvelopeV3Load,
} from './project-v3';

export { captureContent, collectAssetRefsV3 } from './capture';

// The pure runtime-content manifest capture
// plus the canonical/digest helpers the export closure needs. Additive public
// surface recorded as contract-change request C36-2 (docs/handoffs/36.md).
export {
  BUILD_OPTIONS_RECORD,
  MANIFEST_KEYS,
  M2_ENGINE_PINS,
  M2_KNOWN_MODULE_IDS,
  M2_MODULE_PACKAGES,
  RUNTIME_CONTENT_MANIFEST_MAX_BYTES,
  RUNTIME_CONTENT_MANIFEST_VERSION,
  RUNTIME_CONTENT_TYPE,
  buildOptionsRecordBytes,
  captureManifest,
  capturedViewDigest,
  digestBytes,
  digestEmittedClosure,
  manifestBuildIdInput,
  recipeDigestOf,
  requiredModuleIds,
  versionFactsDigest,
  type CaptureManifestInput,
  type CaptureManifestResult,
  type EmittedArtifactDigest,
  type ManifestAssetInput,
  type ManifestBehaviorInput,
  type ManifestError,
  type RuntimeContentManifest,
} from './manifest';
export { canonicalJsonText, sha256Hex, sha256HexOfText,
  sha256HexAsync, sha256Hex as sha256HexBytes } from './sha256';

// The pure manifest v2 derivation — the immutable runtime-content identity,
// the captured v3 content view, the media identity and the strict v2 reader
// + version-compat rule.
export {
  blockDigest,
  captureContentViewV3,
  captureManifestV2,
  M3_ENGINE_PINS,
  M3_KNOWN_MODULE_IDS,
  M3_MODULE_PACKAGES,
  M3_RECIPE_VERSIONS,
  M3_SETTINGS_KEYS,
  MANIFEST_KEYS_V2,
  type ManifestSceneRow,
  type ManifestLibraryRow,
  manifestBuildIdInputV2,
  manifestVersionCompat,
  mediaProfileDigest,
  resolveMediaIdentityV3,
  RUNTIME_CONTENT_MANIFEST_VERSION_4,
  // The manifest's content files.
  MANIFEST_CONTENT_FILE_KEYS,
  MANIFEST_CONTENT_FILE_MAX_BYTES,
  type ManifestContentFileKey,
  type ManifestContentFileRow,
  type ManifestContentFile,
  type ExpandedRuntimeContentManifest,
  validateManifestV2,
  type CapturedAssetV3,
  type CapturedContentViewV3,
  type CaptureManifestV2Input,
  type CaptureManifestV2Result,
  type ManifestAssetInputV2,
  type ManifestMipPart,
  type ManifestErrorV2,
  type MediaAnimationRow,
  type MediaBlock,
  type RuntimeContentManifestV2,
  type ValidateManifestV2Options,
  type ValidateManifestV2Result,
} from './manifest-v2';
// What scenes, models and the project-wide blocks need of the shipped assets (the catalog's dependency lists).
export { dependencyTables, scanDependencies, type DependencyScanTables } from './catalog-dependencies';
export { assetUsers, projectWideRoots, startDrawSet, type MissingAssetFile, type MissingFileUser, type MissingPlayFile } from './missing-files';
// The v5 manifest (identity, start, the catalog's location) and its catalog files.
export {
  captureManifestV5,
  catalogBlockProblem,
  catalogEntriesProblem,
  catalogRootProblem,
  CATALOG_BLOCK_KEYS,
  CATALOG_PART_BYTES,
  CATALOG_SHARD_ENTRIES,
  joinCatalogParts,
  manifestBuildIdInputV5,
  restampManifestV5,
  MANIFEST_KEYS_V5,
  readRuntimeContentSync,
  RUNTIME_CONTENT_MANIFEST_VERSION_5,
  validateManifestV5,
  type CatalogBlockKey,
  type CatalogBlockRow,
  type CatalogEntry,
  type CatalogFile,
  type CatalogFileRef,
  type CatalogRootV5,
  type CatalogSceneRow,
  type CatalogShardRow,
  type CaptureManifestV5Input,
  type CaptureManifestV5Result,
  type CaptureSceneV5,
  type ExpandedRuntimeContent,
  type ManifestAssetInputV5,
  type RuntimeContentManifestV5,
} from './manifest-v5';

export { serializeCanonical } from './normalize';

// The engine module registry + the declared-dependency resolver.
export {
  BEHAVIOR_PACKAGE_MODULES,
  ENGINE_MODULES,
  ENGINE_MODULE_IDS,
  resolveRequiredModules,
  type EngineModule,
  type ResolveModulesInput,
  type ResolveModulesResult,
  type UnresolvedModule,
} from './modules';

// v4 projects — several scenes, one file each.
export {
  composeV4,
  composeSceneV4,
  migrateProjectV3ToV4,
  validateManifestV2Project,
  validateProjectV4,
  MIGRATED_SCENE_NAME,
  type MigrationV4Result,
  type ProjectManifestV2,
  type ProjectV4,
} from './project-v4';
// The project format after the engine/game separation (the loader's upgrade).
export {
  PROJECT_SCHEMA_VERSION,
  PROJECT_SCHEMA_VERSION_UPGRADED,
  PROJECT_SCHEMA_VERSION_V24,
  PROJECT_SCHEMA_VERSION_V25,
  PROJECT_SCHEMA_VERSION_PROJECT_LOOK,
  PROJECT_SCHEMA_VERSION_SCENE_CAMERA,
  isUpgradedProjectSchemaVersion,
  REMOVED_FROM_ENGINE,
  REMOVED_COMPONENTS,
  removedComponentMessage,
  isRemovedComponent,
  upgradeProjectDocsV24,
  type UpgradeV24Result,
} from './upgrade-v24';
// project.json schemaVersion 4 (a 3 is upgraded on load without changing a document).
export { upgradeProjectDocsV25, type UpgradeV25Result } from './upgrade-v25';
// project.json schemaVersion 6 (a 5's project-wide look is copied into every scene on load).
export { upgradeSceneEnvironments, type UpgradeSceneEnvironmentResult } from './upgrade-scene-environment';
export { upgradeSceneModel, sceneCameraAsShot, sceneCamerasAsShots, type UpgradeSceneModelResult } from './upgrade-scene-model';
// The materials a game uses (the manifest leaves the others out).
export { materialsInUse, type MaterialUseInput } from './material-use';
// The assigned entity ids (at least six digits; four-digit ids still load).
export { ENTITY_ID_DIGITS, ENTITY_ID_MAX, entityIdAt, nextFreeEntityIdOf } from './entity-ids';
export { validateSceneV4, validateMergedSceneV4, validateInstancesComponent, DIRECTIONAL_SHADOW_DEFAULTS, DIRECTIONAL_SHADOW_LIMITS, ENTITY_FLAGS, MAX_ENTITIES_V4, V4_REGISTRY } from './scene-v3';
export { validateContentV4, isNormalizedContent, ENGINE_TIMING_DEFAULTS } from './content';
// Texture arrays and packed textures.
export { arrayTextureIds, TEXTURE_ARRAY_KIND, MAX_TEXTURE_LAYERS, KTX2_ENCODINGS, canonicalLabels, isAssetLabel, type Ktx2Encoding } from './content';
// Addresses and labels: what a script may load by name (assets on their records, resources beside theirs).
export { canonicalLoadable, ENV_PRESETS_LIST, isAddress, isLoadable, liveLoadable, loadableAssetIds, loadableResourceIds, loadableRows, loadableRowsProblem, RESOURCE_KIND_TABLE, resourceKindDef, resourceRecordsOf, type LoadableEntry, type LoadableRow, type ResourceKindDef } from './loadable';
// Prefabs spawned into a running game (the snapshot/manifest carry them).
export { PREFAB_V4_COMPONENTS, canonicalPrefabs, validatePrefabDefinitions } from './content';
export { declarationBytes } from './content-behaviors';
export {
  INSTANCE_FLOATS,
  MAX_INSTANCES,
  type ContentCatalogV4,
  type SceneIndexEntry,
  type InstancesComponent,
  type SceneV4,
} from './types-v3';
// Gameplay building blocks.
export {
  BLOCK_COMPONENT_NAMES,
  BLOCK_COMPONENTS,
  // The blocks' tuning defaults and ranges.
  BLOCK_DEFAULTS,
  BLOCK_TUNING_LIMITS,
  MOVER_MODES,
  SWITCH_MODES,
  // Trigger shapes and modes.
  TRIGGER_MODES,
  TRIGGER_RADIUS,
  TRIGGER_SHAPES,
  TRIGGER_HEIGHT,
  // The generic primitives.
  PATROL_MODES,
  HITBOX_SHAPES,
  PRIMITIVE_DEFAULTS,
  PRIMITIVE_LIMITS,
  type CollectibleComponent,
  // Scene transitions, switch actions, face-velocity models.
  FACE_MOVEMENT_MODES,
  MAX_TRANSITION_UNLOADS,
  MAX_TRANSITION_FADE,
  SWITCH_DEFAULT_ACTION,
  type SceneTransitionAction,
  type PatrolComponent,
  type HitboxComponent,
  // Climb volumes and gravity bodies.
  GRAVITY_SCALE,
  type ClimbVolumeComponent,
  type GravityComponent,
  type BlockComponentName,
  type AudioSourceComponent,
  type FaceMovementComponent,
  type HealthComponent,
  type MoverComponent,
  type SwitchComponent,
  type TriggerComponent,
} from './blocks';
// The one counter-name rule (scripts, collectibles and the save loader).
export { COUNTER_NAME_RE, COUNTER_NAME_RULE, isCounterName } from './counter-names';
// The generic node-graph model and the registered graph kinds.
export {
  applyGraphOps,
  canonicalGraphData,
  canonicalGraphDocuments,
  findCycle,
  GRAPH_AUTO_TYPE,
  GRAPH_ITEM_ID_RE,
  graphAssetRefs,
  graphDocumentsContext,
  graphInterface,
  resolveGraphPorts,
  repeatedPorts,
  repeatItems,
  staticNodePorts,
  GRAPH_LIMITS,
  GRAPH_CURVE_LIMITS,
  curveValueError,
  gradientValueError,
  GRAPH_OP_NAMES,
  nodeDef,
  nodeFieldValue,
  nodePorts,
  portCompatibility,
  validateGraphData,
  validateGraphDocument,
  validateGraphDocuments,
  validateGraphOps,
  wouldCycle,
  type GraphComment,
  type GraphContext,
  type GraphConversion,
  type GraphInterfaceDef,
  type GraphNodePorts,
  type GraphPortTypeRule,
  type GraphPortRepeat,
  type GraphData,
  type GraphDocument,
  type GraphEdge,
  type GraphFieldDef,
  type GraphGroup,
  type GraphKindDef,
  type GraphNode,
  type GraphNodeDef,
  type GraphOp,
  type GraphOpsResult,
  type GraphPoint,
  type GraphPortDef,
  type GraphPortRef,
  type GraphPortType,
  type GraphValue,
} from './graph';
export { ANIMATOR_BLEND_GRAPH_KIND, ANIMATOR_GRAPH_KIND, ANIMATOR_LAYER_GRAPH_KIND, GRAPH_KINDS, TEST_GRAPH_KIND } from './graph-kinds';
// Visual scripts (the `behavior` graph kinds, their node catalogue and compile checks).
export {
  BEHAVIOR_API_NODES,
  CALLBACK_EVENT_NODES,
  BEHAVIOR_DATA_TYPES,
  BEHAVIOR_FUNCTION_GRAPH_KIND,
  BEHAVIOR_FUNCTION_ID_RE,
  BEHAVIOR_FUNCTION_KIND,
  BEHAVIOR_GRAPH_KIND,
  BEHAVIOR_GRAPH_LIMITS,
  BEHAVIOR_LIBRARY_GRAPH_KIND,
  BEHAVIOR_LIBRARY_KIND,
  BEHAVIOR_VALUE_TYPES,
  BEHAVIOR_VARIABLE_KINDS,
  BEHAVIOR_VARIABLE_NAME_RE,
  DATA_TYPE_DEFAULT,
  REQUIRED_CORE_FIELDS,
  VARIABLE_PORT_TYPE,
  VARIABLE_PROPERTY_TYPE,
  axesOptions,
  behaviorApiSpec,
  behaviorFunctionInterface,
  behaviorGraphContext,
  behaviorGraphDeclaration,
  behaviorNodePhases,
  behaviorOwnedTransforms,
  behaviorScriptGraphs,
  calleeScope,
  checkBehaviorGraph,
  enumOptions,
  eventPhase,
  isVariableAccess,
  parseVariableValue,
  scopedNodeId,
  variableLabel,
  variableNodesOf,
  variableProperty,
  variableTypeOf,
  variableVisibility,
  type BehaviorFunctionRecord,
  type BehaviorGraphProblem,
  type BehaviorScriptEnv,
  type BehaviorScriptGraph,
  type BehaviorValueType,
  type BehaviorVariableKind,
} from './behavior-graph';
export { BEHAVIOR_API_SKIPPED } from './behavior-api.generated';
export type { BehaviorApiArg, BehaviorApiNodeSpec, BehaviorApiOutput, BehaviorApiStep, BehaviorApiValue, BehaviorDataType } from './behavior-api';
// Shared script libraries (content.scriptLibraries) and behavior library pins.
export {
  SCRIPT_LIBRARY_ENTRY,
  SCRIPT_LIBRARY_IMPORT_PREFIX,
  SCRIPT_LIBRARY_LIMITS,
  applyScriptLibraryPatch,
  canonicalScriptLibraries,
  canonicalScriptLibrary,
  scriptLibraryContainerText,
  scriptLibraryDependents,
  scriptLibraryDigest,
  scriptLibraryPathProblem,
  scriptLibrarySetKey,
  validateLibraryPins,
  validateScriptLibraries,
  validateScriptLibrary,
} from './script-libraries';
export type { BehaviorLibraryPin, ScriptLibrary, ScriptLibraryFile, ScriptLibraryPatch } from './script-libraries';
// Project UI documents and themes (content.uiDocuments / uiThemes, shell.screens).
export {
  UI_EASINGS,
  UI_ENGINE_ACTIONS,
  UI_DEPRECATED_ENGINE_ACTIONS,
  UI_GENERIC_FONTS,
  UI_LIMITS,
  UI_SAVE_SLOTS,
  UI_SCALE_MODES,
  UI_SOUND_EVENTS,
  UI_SHELL_SCREENS,
  UI_TWEEN_KINDS,
  UI_WIDGET_TYPES,
  canonicalUiDocument,
  canonicalUiDocuments,
  canonicalUiTheme,
  canonicalUiThemes,
  uiAssetRefs,
  uiBindPathProblem,
  uiDocumentsForRuntime,
  uiItemKeyProblem,
  uiTextPlaceholders,
  validateUiDocument,
  validateUiDocuments,
  validateUiReferences,
  validateUiStyle,
  validateUiTheme,
  validateUiThemes,
} from './ui-documents';
export type { RuntimeUiDocumentRow, UiAction, UiBindable, UiBinding, UiColor, UiDocument, UiDocumentRefs, UiEasing, UiEngineAction, UiIcon, UiScalar, UiScaleMode, UiSounds, UiStyle, UiStyleValues, UiTheme, UiTween, UiTweenKind, UiWidget, UiWidgetType, UiWorldAnchor } from './ui-documents';
export { UI_DESCRIPTORS, type UiDescriptors } from './ui-descriptors';
// Visual effects (content.effects, the effect component) and the effect graph kind.
export {
  EFFECT_ATTRIBUTES,
  EFFECT_ATTRIBUTE_TYPES,
  EFFECT_BLEND_MODES,
  EFFECT_CONTEXTS,
  EFFECT_CONTEXT_FLOWS,
  EFFECT_CONTEXT_LAYOUT,
  EFFECT_EVENTS,
  EFFECT_GRAPH_KIND,
  EFFECT_GRAPH_LIMITS,
  EFFECT_LIGHT_LIMIT,
  EFFECT_SHADING,
  EFFECT_VALUE_TYPES,
  effectFieldDefault,
  newEffectSystemGraph,
  type EffectContext,
  type EffectValueType,
} from './effect-graph-kinds';
export {
  EFFECT_DEFAULTS,
  EFFECT_LIMITS,
  EFFECT_PARAMETER_TYPES,
  canonicalEffect,
  canonicalEffectComponent,
  canonicalEffects,
  effectAssetRefs,
  effectComponentErrors,
  effectMaterialRefs,
  effectsForRuntime,
  effectGraphContext,
  effectParameterPortType,
  effectParameterValueError,
  effectSystemOwnerId,
  parseEffectSystemOwnerId,
  validateEffect,
  validateEffectComponent,
  validateEffectParameters,
  validateEffects,
  type EffectComponent,
  type EffectDef,
  type EffectParameter,
  type EffectParameterType,
  type EffectSystem,
} from './effects';
// The camera framework's data (virtual cameras and camera paths).
export {
  CAMERA_BLENDS,
  CAMERA_PATH_FIELDS,
  CAMERA_PATH_LIMITS,
  CAMERA_RAIL_MODES,
  VIRTUAL_CAMERA_DEFAULTS,
  VIEW_LENS_DEFAULTS,
  DEFAULT_VIEW_POSE,
  DEFAULT_VIEW_ID,
  viewLensOf,
  VIRTUAL_CAMERA_FIELDS,
  VIRTUAL_CAMERA_LIMITS,
  VIRTUAL_CAMERA_RIGS,
  canonicalCameraPath,
  canonicalVirtualCamera,
  validateCameraPathComponent,
  validateVirtualCameraComponent,
  CAMERA_REGION_DEFAULTS,
  CAMERA_REGION_FIELDS,
  CAMERA_REGION_LIMITS,
  canonicalCameraRegion,
  validateCameraRegionComponent,
  type CameraRegionComponent,
  type CameraBlendStyle,
  type CameraPathComponent,
  type CameraRailMode,
  type VirtualCameraComponent,
  type VirtualCameraRig,
} from './cameras';
// Sockets (an entity on a node of another entity's model) and model rigs as simulation data.
export {
  SOCKET_ATTACH_CONFLICTS,
  SOCKET_ATTACH_FIELDS,
  SOCKET_ATTACH_LIMITS,
  canonicalSocketAttach,
  validateSocketAttachComponent,
  type SocketAttachComponent,
} from './sockets';
export {
  MODEL_RIG_LIMITS,
  quatFromRotation,
  readModelRig,
  rigNodeNames,
  sanitizeRigNodeName,
  validateModelRig,
  type ModelRig,
  type ModelRigChannel,
  type ModelRigClip,
  type ModelRigNode,
  type RigInterpolation,
  type RigPath,
} from './model-rig';
// The material node catalogue (material graphs and material functions).
export { MATERIAL_BUILTIN_SOURCES, MATERIAL_DATA_MAX, MATERIAL_FUNCTION_GRAPH_KIND, MATERIAL_GRAPH_KIND, MATERIAL_PARAMETER_TYPES, MATERIAL_VALUE_TYPES, type MaterialParameterType } from './material-graph-kinds';
// An animator controller's layers and blend trees as graphs (owner kind `animator`).
export { animatorGraphOf, animatorTransitionPairs, applyAnimatorGraph, parseAnimatorOwnerId, type AnimatorGraphWrite, type AnimatorOwnerTarget } from './animator-graph';
// Input actions.
export {
  canonicalInput,
  DEFAULT_INPUT,
  DEFAULT_INPUT_3D,
  defaultInputFor,
  INPUT_ACTION_TYPES,
  INPUT_MAPS,
  MAX_INPUT_ACTIONS,
  validateInput,
  type InputAction,
  type InputActionType,
  type InputBinding,
  type InputConfig,
  // Pointer bindings and the cursor per map.
  CURSOR_MODES,
  POINTER_AXES,
  POINTER_BUTTONS,
  type CursorMode,
  type PointerAxisName,
  type PointerButtonName,
  // The project's own input maps.
  MAX_INPUT_MAPS,
  projectInputMaps,
  type InputMapName,
  // The hold modifier and the project's glyph images.
  GAMEPAD_FAMILIES,
  GLYPH_KEY_RE,
  HOLD_BINDING_KINDS,
  PAD_BINDING_KINDS,
  INPUT_PAD_SLOTS,
  INPUT_HOLD_MAX,
  INPUT_HOLD_MIN,
  MAX_INPUT_GLYPHS,
} from './input';
// Game modes (content.modes), behavior groups and the behaviorGroup component.
export {
  MODE_BLENDS,
  MODE_DEFAULTS,
  MODE_LIMITS,
  MODE_NAME_RE,
  MODE_PHYSICS,
  MODE_UNGROUPED,
  behaviorGroupErrors,
  canonicalBehaviorGroup,
  canonicalMode,
  canonicalModes,
  modesForRuntime,
  validateBehaviorGroupComponent,
  validateBehaviorGroups,
  validateMode,
  validateModeReferences,
  validateModes,
  validateModeTransition,
} from './modes';
export type { BehaviorGroupComponent, GameMode, ModeBlend, ModePhysics, ModeTransition, ModeUngrouped, RuntimeModes } from './modes';
// The event → cue table.
export { ENGINE_EVENT_TYPES, EVENT_CUE_BUSES, EVENT_CUE_FIELDS, EVENT_CUE_LIMITS, EVENT_CUE_SOURCES, canonicalEventCue, canonicalEventCues, validateEventCue, validateEventCueReferences, validateEventCues, type EventCue } from './event-cues';
export { SHELL_FIELDS, SHELL_LIMITS, SHELL_SCREENS, SHELL_SIMULATE, canonicalShell, validateShell, validateShellReferences, type GameShell, type ShellScene, type ShellScreen, type ShellSimulate } from './shell';
// The old modelAnimation profile becomes an animator controller on open.
export { glbClipDurations, LEGACY_CROSSFADE_SECONDS, LEGACY_RUN_SPEED_EPS, migrateModelAnimations, type ClipDurationOf, type ModelAnimationMigration } from './animator-migrate';
// Animator controllers.
export {
  ANIMATOR_CONDITION_OPS,
  ANIMATOR_PARAMETER_TYPES,
  ANIMATOR_RESERVED_GRAPH_ID_RE,
  animatorAssetIds,
  animatorsForRuntime,
  animatorStates,
  canonicalAnimatorController,
  canonicalAnimators,
  MAX_ANIMATOR_LAYERS,
  LOOK_AT_LIMITS,
  MAX_BLEND_GROUND_SPEED,
  MAX_LAYER_MASK,
  validateAnimatorComponent,
  validateAnimatorController,
  validateAnimators,
  type AnimatorBlendChild,
  type AnimatorClipRef,
  type AnimatorComponent,
  type AnimatorCondition,
  type AnimatorConditionOp,
  type AnimatorController,
  type AnimatorEvent,
  type AnimatorLayer,
  type AnimatorLayout,
  type AnimatorLookAt,
  type AnimatorLookAtBone,
  type AnimatorMotion,
  type AnimatorParameter,
  type AnimatorParameterType,
  type AnimatorState,
  type AnimatorTransition,
} from './animator';
// Baked lighting.
export {
  canonicalLighting,
  LIGHTMAP_SOURCES,
  MAX_LIGHTMAP_ATLASES,
  MAX_LIGHTMAP_ENTRIES,
  MAX_BAKED_LIGHTS,
  validateLighting,
  validateLightingBake,
  type LightingBake,
  type LightingEntry,
  type LightingMap,
} from './lighting';
// Probe grids (baked indirect light).
export * from './probe-grids';
// Materials, material mappings and the environment (a scene's look, the project's quality and presets).
export {
  canonicalEnvironment,
  canonicalMaterialMapping,
  canonicalMaterials,
  DEFAULT_WIND,
  MATERIAL_PARAMS,
  MATERIAL_SHADERS,
  MATERIAL_SLOT_ALL,
  MATERIAL_TEXTURE_SLOTS,
  materialParamError,
  // Graph materials (exposed parameters, the graph, the runtime view).
  canonicalMaterialParameters,
  MATERIAL_PARAMETER_KEY_RE,
  materialGraphContext,
  materialParameterPortType,
  materialParameterValueError,
  materialsForRuntime,
  materialFunctionsForRuntime,
  materialTextureRefs,
  graphForRuntime,
  MAX_MATERIAL_PARAMETERS,
  MATERIAL_EXTRA_LAYERS_MAX,
  validateMaterialGraph,
  validateMaterialParameters,
  canonicalMaterialParams,
  materialOverrideErrors,
  validateMaterialParamsComponent,
  type MaterialParamsComponent,
  type MaterialParameter,
  type MaterialParameterValue,
  type MaterialValue,
  MAX_MATERIAL_SLOTS,
  validateEnvironment,
  validateQualityLevels,
  validateMaterialMapping,
  validateMaterials,
  // Material instances.
  MAX_MATERIAL_INSTANCE_DEPTH,
  resolveMaterial,
  resolveMaterialInstances,
  validateMaterialInstances,
  validateFogVolumeComponent,
  MAX_FOG_VOLUMES,
  canonicalSceneEnvironment,
  environmentTextureRefs,
  SCENE_ENVIRONMENT_FIELDS,
  SKY_ROTATION_MAX,
  sceneEnvironmentIsEmpty,
  validateSceneEnvironment,
  type SceneEnvironment,
  type EnvironmentConfig,
  type FogConfig,
  type HeightFogConfig,
  HEIGHT_FOG_DEFAULTS,
  HEIGHT_FOG_LIMITS,
  validateHeightFog,
  type FogVolumeComponent,
  type PostConfig,
  type SkyConfig,
  type MaterialDef,
  type MaterialParamType,
  type MaterialParamValue,
  type MaterialShader,
  type WindConfig,
  WET_ALBEDO_SCALE,
  WET_ROUGHNESS,
} from './materials';
// Per-layer texture slots of graph materials (Play and the export assemble arrays from them).
export { hasTextureSlots, isTextureSlots, materialSlotTextureRefs, materialTextureSlotSets, parseTextureSlotSetKey, textureSlotLayers, textureSlotMode, textureSlotSetKey, textureSlotsError, withAssembledSlots, type TextureSlotSet } from './texture-slots';

// Environment presets (named looks scripts switch or blend to).
export {
  ENVIRONMENT_LIGHT_TYPES,
  ENVIRONMENT_PRESET_LIMITS,
  canonicalEnvironmentPresets,
  environmentPresetTextureRefs,
  validateEnvironmentPatch,
  validateEnvironmentPresets,
  type EnvironmentLightType,
  type EnvironmentLookParts,
  type EnvironmentPreset,
  type EnvironmentPresetLight,
  type EnvironmentPresetLightmap,
} from './environment-presets';

// The component and content descriptor registry (pure data).
export {
  ASSET_KINDS,
  COMPONENT_ICONS,
  DESCRIPTORS,
  HANDLE_KINDS,
  HANDLE_ROLES,
  type AssetRefFieldDescriptor,
  type BoolFieldDescriptor,
  type ColorFieldDescriptor,
  type ComponentAdd,
  type ComponentDescriptor,
  type ComponentIcon,
  type CreateEntryDescriptor,
  type ComponentRelation,
  type ComponentsFieldDescriptor,
  type ContentBlockDescriptor,
  type DescriptorAssetKind,
  type DescriptorJson,
  type DescriptorRefTarget,
  type DescriptorRegistry,
  type DescriptorScalar,
  type DescriptorStringFormat,
  type DescriptorUnit,
  type EntityRefFieldDescriptor,
  type EnumFieldDescriptor,
  type EnumOption,
  type FieldCondition,
  type FieldDescriptor,
  type FieldType,
  type HandleDescriptor,
  type HandleKind,
  type IntFieldDescriptor,
  type JsonFieldDescriptor,
  type ListFieldDescriptor,
  type MapFieldDescriptor,
  type NumberFieldDescriptor,
  type ObjectFieldDescriptor,
  type QuatFieldDescriptor,
  type RefFieldDescriptor,
  type SceneRefFieldDescriptor,
  type SignalFieldDescriptor,
  type StringFieldDescriptor,
  type VecFieldDescriptor,
} from './descriptors';

// Generic component access for scripts (ctx.entity): the table and the write check.
export {
  SCRIPT_ACCESS_SCHEMA_VERSION,
  SCRIPT_OBJECT_COMPONENT,
  checkScriptPatch,
  scriptAccessTable,
  scriptComponentAccess,
  scriptSnapshot,
  type ScriptAccessTable,
  type ScriptComponentAccess,
  type ScriptPatchResult,
  type ScriptWriteCode,
  type ScriptWriteProblem,
} from './script-fields';

// Block layers — data model, grid, edits, meshing, PNG heightmaps.
export {
  BLOCK_LAYER_DEFAULT,
  BLOCK_LIMITS,
  BLOCK_SHAPES,
  BLOCK_UV_MODES,
  CELL_FIELD_KEY_RE,
  CELL_FIELD_TYPES,
  CHUNK_SIZE,
  REGION_ID_RE,
  blockCellKey,
  blockTypeSolid,
  blockVariantUv,
  canonicalBlockCell,
  canonicalBlockChunk,
  canonicalBlockLayerComponent,
  canonicalBlockFootprint,
  validateBlockFootprintComponent,
  BLOCK_FOOTPRINT_MAX,
  type BlockFootprintComponent,
  canonicalBlockStamp,
  canonicalBlockStamps,
  canonicalBlockType,
  canonicalBlockTypes,
  canonicalCellFields,
  canonicalRuns,
  canonicalSceneBlocks,
  cellFieldDefault,
  cellFieldValueError,
  composeBlockContent,
  composeBlockLayers,
  rotatedFootprint,
  blockTypeSlopes,
  BLOCK_CORNER_STEPS,
  BLOCK_CORNER_MAX,
  BLOCK_LAYER_FIELDS,
  BLOCK_MAX_SLOPE_RANGE,
  BLOCK_SMOOTH_ANGLE_RANGE,
  BLOCK_TOP_SUBDIVISIONS,
  validateBlockCell,
  validateBlockLayerComponent,
  validateBlockRegion,
  validateBlockStamp,
  validateBlockStamps,
  validateBlockType,
  validateBlockTypes,
  validateCellFields,
  validateSceneBlocks,
  type BlockCell,
  type BlockChunk,
  type BlockContentView,
  type BlockLayerComponent,
  type BlockLayerData,
  type BlockRegion,
  type BlockShape,
  type BlockUvMode,
  type BlockStamp,
  type BlockType,
  type BlockVariant,
  type CellField,
  type CellFieldType,
  type CellMetaValue,
} from './block-layers';
export {
  BLOCK_EDIT_KINDS,
  BLOCK_EDIT_MAX_CELLS,
  BLOCK_COLUMN_BYTES,
  BLOCK_EDGE_BYTES,
  BLOCK_EDIT_MAX_EDITS,
  PAINT_TARGETS,
  SURFACE_EDIT_MAX_COLUMNS,
  blockEditsShapeError,
  BlockGrid,
  applyBlockEdits,
  autoVariant,
  boxContains,
  cellCenter,
  cellKeyOf,
  cellOfKey,
  chunkKeyOf,
  compareChunkKeys,
  edgeAutoVariant,
  effectiveCellMeta,
  pickCell,
  regionCells,
  regionContains,
  subtractBox,
  worldToCell,
  type BlockEdit,
  type BlockEditContext,
  type BlockEditResult,
  type BlockGridReader,
  type BlockLayerMemory,
  type BlockPick,
  type BlockRotation,
  type PaintTarget,
  type Vec3Like,
} from './block-grid';
export {
  COLLISION_PIECE_LIMITS,
  WORLD_UV_PERIOD_METRES,
  blockTopOptions,
  chunkOfCell,
  collisionMeshChunk,
  meshBlockChunk,
  shapeSource,
  type BlockLookResolver,
  type BlockMeshSource,
  type BlockTopOptions,
  type ChunkMeshPart,
  type CollisionMeshPiece,
} from './block-mesh';
export { SCULPT_LIMITS, SCULPT_OPS, columnHeights, sculptHeights, setColumnSurface, type ColumnHeights, type SculptDab, type SculptOp } from './block-sculpt';
// The paint brush (any paint target) and a block layer's surface paint.
export { BRUSH_FALLOFFS, PAINT_BRUSH_LIMITS, brushFalloff, paintBrushError, paintPoint, type BrushFalloff, type PaintBrush, type PaintLayout } from './paint-brush';
export {
  BLOCK_EDGE_SHAPES,
  BLOCK_EDGE_SIDES,
  BLOCK_EDGE_THICKNESS,
  BLOCK_PLACEMENTS,
  blockTypeIsEdge,
  canonicalBlockEdge,
  edgeBlocks,
  edgeCollides,
  edgeFrame,
  edgeInBounds,
  edgeInBox,
  edgeLookMetres,
  edgeOfSide,
  liveEdgePlacement,
  sideOfAxis,
  validateBlockEdge,
  type BlockEdge,
  type BlockEdgeAxis,
  type BlockEdgeSide,
  type BlockPlacement,
  transformEdge,
  type EdgesEdit,
} from './block-edges';
export {
  BLOCK_CONNECT_PIECES,
  BLOCK_CONNECT_WITH_MAX,
  BLOCK_EDGE_CONNECT_PIECES,
  blockTypeConnects,
  cellConnectNeighbours,
  edgeConnectNeighbours,
  edgeEnds,
  resolveCellLook,
  resolveEdgeLook,
  type BlockConnect,
  type BlockConnectLook,
  type BlockConnectPiece,
  type ConnectedLook,
  type ConnectGrid,
} from './block-connect';
export { LIVE_BLOCK_PREFAB_REFUSED, LIVE_BLOCK_ROOT_MERGED, LIVE_BLOCK_ROOT_REFUSED, blockTypeLive, liveBlockIds, liveBlockPlacement, liveBlockPrefabProblem, liveBlockPrefix, liveBlockRootId, liveEdgeRootId } from './block-live';
export { chunkMeshPaint, type ChunkPaintOptions, type PaintedGeometry } from './block-paint-mesh';
export { chunkMeshAO, type AoGeometry } from './block-ao';
export { UNPAINTED_WALL, WALL_PAINT_MAX_STEPS, WALL_PAINT_STEP_METRES, WALL_POINT_BYTES, WALL_SIDE_AXES, canonicalWallPaint, decodeWallPaint, encodeWallPaint, wallPaintAt, wallPaintDab, wallPaintError, wallPaintSteps, wallPointKey, wallPointOfKey, type WallPaint, type WallPaintSurface, type WallSteps } from './block-wall-paint';
// Trim sheets: the trim material's row table, strip coordinates, mip bounds, padding checks; generated meshes' paint.
export {
  TRIM_COLOUR_GRIME,
  TRIM_COLOUR_OCCLUSION,
  TRIM_COLOUR_WETNESS,
  TRIM_DENSITY_MAX,
  TRIM_DENSITY_MIN,
  TRIM_PADDING_MAX,
  TRIM_SHEET_DEFAULTS,
  TRIM_SHEET_SIZE_MAX,
  TRIM_STARTER_LAYOUT,
  canonicalTrimSheet,
  defaultTrimSheet,
  equalTrimRows,
  trimLayoutMissing,
  trimMaxFootprint,
  trimPaddingProblems,
  trimRowDensity,
  trimRowMetres,
  trimRowOf,
  trimRowV,
  trimSafeMipLevel,
  trimSheetErrors,
  trimSheetFromLayout,
  trimSheetMipLevels,
  trimSheetProblems,
  trimSheetSafeMipLevel,
  trimU,
  trimV,
  writeTrimStripUvs,
  writeTrimVertexColour,
  type TrimLayoutImport,
  type TrimPaddingProblem,
  type TrimRow,
  type TrimSheet,
  type TrimSheetError,
  type TrimSheetProblem,
} from './trim-sheet';
export { TRIM_GRIME_PAINT_LAYER, paintArchitectureColours, trimColoursFromWallPaint, type TrimWallPaintOptions } from './trim-paint';
export { cutWallPolygon, type CutVertex } from './block-wall-cut';
export { CUTAWAY_FADE_RANGE, CUTAWAY_FADE_SECONDS, canonicalBlockCutaway, cutawayCuts, cutawayPlaneKey, cutawaySeams, cutawayZoneKeys, cutawayZones, validateBlockCutaway, type BlockCutaway, type BlockCutawayRegion, type CutawayBox, type CutawayZone } from './block-cutaway';
export { blockKitNames, canonicalBlockTypeKits, canonicalLayerKits, composeBlockTypeKits, kitKey, kitRegionsMissing, kitSwapCollides, kitZones, validateBlockTypeKits, validateLayerKits, type BlockKitSwap, type BlockLayerKit, type KitZone } from './block-kit';
export { BlockKitView, blockKitView, swapBlockCell, swapBlockEdge } from './block-kit-view';
export { BlockWalkGraph, WALK_QUERY_MAX_NODES, findWalkPath, footprintAnchors, walkReach, type WalkGraphOptions, type WalkPathResult, type WalkPlace, type WalkSearchOptions, type WalkSettings, type WalkStep } from './block-walk';
export { WALK_METRES_RANGE, canonicalBlockLayerWalk, defaultWalkSettings, validateBlockLayerWalk, walkSettingsOf, type BlockLayerWalk } from './block-walk-settings';
export { BLOCK_CHECK_EXAMPLES, blockLayerChecks, type BlockCheckCode, type BlockLayerCheck } from './block-checks';
export { BLOCK_PAINT_LAYOUT, PAINT_BYTES, PAINT_CHANNELS, PAINT_CHUNK_SIZE, PAINT_VERTICES, PAINT_WETNESS_CHANNEL, chunkPaintColors, chunkPaintError, chunksOfVertex, decodeChunkPaint, encodeChunkPaint, isUnpainted, paintDab, paintOffset, unpaintedChunk, type PaintSurface } from './block-paint';
export { BLOCK_CHUNK_COMPRESSION, BLOCK_CHUNK_DATA_KEY, BLOCK_CHUNK_HEADER_BYTES, decodeBlockChunks, encodeBlockChunks, readBlockChunkData, wrapBlockChunkData, type BlockChunkCompression } from './block-chunk-binary';
export { BINARY_COMPRESSION, BINARY_HEADER_BYTES, hasBinaryMagic, readBinaryBlob, wrapBinaryBlob, type BinaryCompression } from './binary-container';
export {
  TERRAIN_FIELDS,
  TERRAIN_HEIGHT_LIMIT,
  TERRAIN_HEIGHT_STEPS,
  TERRAIN_LOD_DISTANCE_LIMITS,
  TERRAIN_MACRO_DISTANCE_LIMITS,
  TERRAIN_SPACING_LIMITS,
  TERRAIN_TILE_COORD_MAX,
  TERRAIN_TILE_SAMPLES,
  TERRAIN_TILE_SAMPLES_DEFAULT,
  canonicalTerrain,
  terrainFlatStep,
  terrainHeightOf,
  terrainStepOf,
  terrainTileKey,
  terrainTileSize,
  validateTerrainComponent,
  type TerrainComponent,
  type TerrainTileRef,
} from './terrain';
// Splines: one curve component (roads, rivers, rails) and its curve in the world.
export {
  SPLINE_FALLOFF_DEFAULT,
  SPLINE_FIELDS,
  SPLINE_LIMITS,
  SPLINE_MATERIAL_SLOT,
  SPLINE_MESH_KINDS,
  SPLINE_MESH_STEP_DEFAULT,
  SPLINE_SCATTER_MARGIN_DEFAULT,
  SPLINE_SURFACE_OFFSET_DEFAULT,
  SPLINE_TERRAIN_SHAPES,
  SPLINE_WATER_FLOW_DEFAULT,
  SPLINE_WATER_FOAM_DEFAULT,
  SPLINE_WIDTH_DEFAULT,
  canonicalSpline,
  splineMakesData,
  splinePieceAssets,
  validateSplineComponent,
  type SplineComponent,
  type SplineMeshKind,
  type SplineMeshSettings,
  type SplinePieceSettings,
  type SplinePoint,
  type SplineScatterSettings,
  type SplineTerrainSettings,
  type SplineTerrainShape,
} from './spline';
export { SPLINE_TABLE_STEP, SplineCurve, newSplineFrame, type SplineFrame, type SplineNearest } from './spline-curve';
export { SPLINE_MADE_LAYOUT, SPLINE_MADE_MAGIC, SPLINE_MESH_PIECE_METRES, decodeSplineMade, encodeSplineMade, isSplineMadeBlob, makeSpline, splinePieceCopies, sweepSplineMesh, type SplineMade, type SplineMeshLevel, type SplineMeshPiece } from './spline-mesh';
export { SplineScatterBands, TERRAIN_SPLINE_STEP, TerrainSplineLayer, rasterizeSpline, splineScatterReach, splineScatterRect, terrainSplineInputs, terrainSplineReach, terrainSplineRect, type SplineRaster, type TerrainSplineInput, type TerrainSplinePaint } from './terrain-splines';
export {
  TERRAIN_LAYER_MAX,
  TERRAIN_PAINT_BYTES,
  TERRAIN_SAMPLE_LAYERS,
  TERRAIN_TILE_HEADER_BYTES,
  TERRAIN_TILE_MAGIC,
  TERRAIN_WEIGHT_BYTES,
  cloneTerrainTile,
  decodeTerrainTile,
  encodeTerrainTile,
  flatTerrainTile,
  isTerrainTileBlob,
  readTerrainTileBlob,
  setTerrainHole,
  terrainBakedLayers,
  terrainHoleAt,
  terrainLayersAt,
  terrainTileBlobBytes,
  terrainTileBytes,
  wrapTerrainTile,
  type TerrainTile,
} from './terrain-tile';
// A streamed terrain's overview: every tile at its coarsest level, one blob a build ships.
export {
  TERRAIN_OVERVIEW_SAMPLES,
  decodeTerrainOverview,
  encodeTerrainOverview,
  isTerrainOverviewBlob,
  readTerrainOverviewBlob,
  terrainOverviewTile,
  wrapTerrainOverview,
  type TerrainOverviewTile,
} from './terrain-overview';
// World streaming: rings around the camera within which terrain tiles and block chunks are loaded, a memory budget.
export {
  STREAMING_BUDGET_DEFAULT_MB,
  STREAMING_BUDGET_MAX_MB,
  STREAMING_BUDGET_MIN_MB,
  STREAMING_HYSTERESIS_SHARE,
  STREAMING_RADIUS_LIMITS,
  inStreamRing,
  nearestSquareDistance,
  resolveStreamingRings,
  squareDistance,
  streamingBudgetBytesOf,
  validateStreamingRings,
  type ResolvedStreamingRings,
  type StreamingRings,
  type StreamRing,
} from './world-streaming';
export {
  TERRAIN_BRUSH_LIMITS,
  TERRAIN_NOISE_HASH,
  TERRAIN_SCULPT_KINDS,
  TerrainSamples,
  holeTerrain,
  paintTerrain,
  paintTerrainSample,
  rampTerrain,
  sculptTerrain,
  terrainDabSamples,
  terrainNoise,
  type TerrainHoleDab,
  type TerrainPaintDab,
  type TerrainRamp,
  type TerrainSculptDab,
  type TerrainSculptKind,
} from './terrain-edit';
export { HEIGHTMAP_FORMATS, HEIGHTMAP_MAX_SAMPLES, blockLayerToTerrain, decodeHeightmap, importHeightmap, type BlockLayerSource, type Heightmap, type HeightmapFormat, type HeightmapOptions } from './terrain-import';
export { TerrainField, terrainCellStep, type TerrainSample } from './terrain-field';
// Edit layers: stamps, erosion and the splines combined over the hand-made ground into the drawn heights.
export {
  TERRAIN_LAYER_KINDS,
  TERRAIN_SPLINES_LAYER_ID,
  TERRAIN_STAMP_FALLOFF_DEFAULT,
  TERRAIN_STAMP_MODES,
  TERRAIN_STAMP_SIZE_LIMITS,
  TerrainLayerStack,
  canonicalTerrainLayers,
  decodeTerrainDelta,
  encodeTerrainDelta,
  terrainLayerChangeRects,
  terrainLayerOrder,
  terrainLayerTileDigests,
  terrainStampRect,
  validateTerrainLayers,
  type TerrainBlocksLayer,
  type TerrainErosionLayer,
  type TerrainLayer,
  type TerrainLayerKind,
  type TerrainLayerSources,
  type TerrainLayerTileRef,
  type TerrainSplinesLayer,
  type TerrainStamp,
  type TerrainStampMode,
  type TerrainStampsLayer,
} from './terrain-layers';
// Block layers on a terrain: the ground meets their border, is cut or flattened under them, their paint carries across.
export { TERRAIN_BLOCKS_BLEND_DEFAULT, TERRAIN_BLOCKS_BLEND_LIMITS, TERRAIN_BLOCKS_MODES, TERRAIN_BLOCKS_SINK, TerrainBlockSeam, type BlockSeamSample, type TerrainBlocksMode, type TerrainBlocksSettings, type TerrainBlocksSource } from './terrain-blocks';
export {
  EROSION_FADE_SAMPLES,
  EROSION_LIMITS,
  EROSION_MARGIN_SAMPLES,
  EROSION_MAX_SAMPLES,
  HYDRAULIC_DEFAULTS,
  THERMAL_DEFAULTS,
  erodeGrid,
  validateErosionSettings,
  type ErosionGrid,
  type ErosionSettings,
  type HydraulicErosion,
  type ThermalErosion,
} from './terrain-erosion';
// Material rules: one rule list paints terrain (baked into tiles by its edits) and block layers (at meshing).
export {
  SURFACE_RULE_BLOCK_LAYERS,
  SURFACE_RULE_CAVITY_RADIUS,
  SURFACE_RULE_FIELDS,
  SURFACE_RULE_LAYER_MAX,
  SURFACE_RULE_LIMITS,
  SurfaceRuleSet,
  canonicalSurfaceRules,
  ruleConditionsAt,
  ruleNoise,
  ruleRangeAt,
  validateSurfaceRules,
  type RuleRange,
  type SurfacePoint,
  type SurfaceRule,
} from './surface-rules';
export { bakeTerrainRules, terrainBakeMargin, terrainBakeRect, type TerrainBakeOver, type TerrainSampleRect } from './terrain-rules';
// Rule scatter: models placed by rules on terrain (copies baked per tile) and block layers (per chunk).
export {
  FOLIAGE_NEAR_METRES,
  SCATTER_BAKE_MAX_CANDIDATES,
  SCATTER_BLOB_DISTANCE,
  SCATTER_BLOB_MAGIC,
  SCATTER_CHUNK_METERS_DEFAULT,
  SCATTER_COPY_FLOATS,
  SCATTER_COVER_DISTANCE_DEFAULT,
  SCATTER_LIMITS,
  SCATTER_RULE_FIELDS,
  bakeScatterCell,
  canonicalScatterRules,
  chunkScatterError,
  coverScatterRules,
  decodeChunkScatter,
  decodeScatterCell,
  encodeChunkScatter,
  encodeScatterCell,
  sameScatterCell,
  scatterCellBytes,
  scatterCellCopies,
  scatterReach,
  scatterRuleAssets,
  scatterStrokeRect,
  storedScatterRules,
  strokeScatterEdits,
  validateScatterRules,
  withScatterEdits,
  type ScatterBakeResult,
  type ScatterCell,
  type ScatterCopies,
  type ScatterGround,
  type ScatterLayerCondition,
  type ScatterRect,
  type ScatterRule,
  type ScatterStroke,
  type ScatterSurface,
} from './scatter';
export { blockScatterSurface, regionExcluder, terrainScatterSurface, type BlockScatterSource, type ScatterRegionLayer } from './scatter-surfaces';
export { SURFACE_TIE_METRES, surfaceAt, type SurfaceAt, type SurfaceBlockSource, type SurfaceSource, type SurfaceTerrainSource } from './surface-query';
export { bakeTerrainScatter, isScatterBlob, scatterBlobOf, scatterCellOfBlob, terrainChangedSamples, terrainTileRect } from './terrain-scatter';
export { bakeBlockScatter, blockChunkRect, type BlockScatterContext, type BlockScatterStroke } from './block-scatter';
export { architectureShipsMeshesOf, blockChunkStorageOf, maxSlopeClimbOf } from './content-settings';
// Generated architecture: parameters in the scene, geometry made at load (sweeps, repeats and fills on a trim sheet).
export {
  ARCHITECTURE_AO_DEFAULTS,
  ARCHITECTURE_CHUNK_DEFAULT,
  ARCHITECTURE_ELEMENT_KINDS,
  ARCHITECTURE_FIELDS,
  ARCHITECTURE_FILL_SHAPES,
  ARCHITECTURE_LIMITS,
  ARCHITECTURE_LOD_DISTANCE_DEFAULT,
  ARCHITECTURE_MATERIAL_SLOT,
  ARCHITECTURE_PANE_MATERIAL_SLOT,
  ARCHITECTURE_STAIR_RISER,
  ARCHITECTURE_STEP_DEFAULT,
  ARCHITECTURE_DOOR_SILL_MAX,
  ARCHITECTURE_DOOR_SPAWN_DISTANCE,
  ARCHITECTURE_ROOF_OVERHANG_DEFAULT,
  ARCHITECTURE_ROOF_SHAPES,
  ARCHITECTURE_ROOF_SLOT_DEFAULT,
  architectureMaterialSlots,
  architectureModelAssets,
  canonicalArchitecture,
  validateArchitectureComponent,
  type ArchitectureComponent,
  type ArchitectureElement,
  type ArchitectureFill,
  type ArchitectureFillShape,
  type ArchitectureFloorHole,
  type ArchitectureModelRef,
  type ArchitecturePaint,
  type ArchitectureStair,
  type ArchitectureOpening,
  type ArchitectureMask,
  type ArchitectureOutline,
  type ArchitectureOverride,
  type ArchitecturePath,
  type ArchitectureProfile,
  type ArchitectureRepeat,
  type ArchitectureSweep,
  type ArchitectureBuilding,
  type ArchitectureBuildingInterior,
  type ArchitectureInteriorOf,
  type ArchitectureRoof,
  type ArchitectureRoofShape,
  type ArchitecturePin,
} from './architecture';
// Buildings whose interiors are scenes of their own: the interior made there, the doors' links.
export { architectureDoorLinks, buildingInteriorEntity, buildingInteriorId, isBuildingDoor, withBuildingInteriors, type ArchitectureDoorLink, type ArchitectureDoorSide, type BuildingSourceEntity } from './arch-buildings';
export { largestRectangles } from './arch-roof';
export {
  ARCHITECTURE_COPY_FLOATS,
  ARCHITECTURE_GENERATOR_VERSION,
  ARCHITECTURE_SWEEP_CELL,
  architectureChunkInput,
  architectureSheets,
  architectureChunkKeys,
  architectureChunks,
  architectureColliders,
  architectureCopies,
  generateArchitecture,
  generateArchitectureChunk,
  joinArchitectureChunkParts,
  sheetFor,
  trimSheetOfMaterial,
  type ArchitectureChunk,
  type ArchitectureChunkKey,
  type ArchitectureChunkPart,
  type ArchitectureChunkMesh,
  type ArchitectureCollider,
  type ArchitectureCopySet,
  type ArchitectureMeshBounds,
  type ArchitectureSheets,
} from './arch-generate';
export { ARCHITECTURE_BLOB_LAYOUT, ARCHITECTURE_BLOB_MAGIC, decodeArchitectureChunks, encodeArchitectureChunks, isArchitectureBlob } from './arch-blob';
export type { ArchMeshArrays } from './arch-mesh';
// Architecture styles (graphs of the generator's operators) and presets (a style plus values, deriving from presets).
export { ARCHITECTURE_GRAPH_NODES, ARCHITECTURE_MASK_SOURCES, ARCHITECTURE_PRESET_GRAPH_KIND, ARCHITECTURE_PRESET_KIND, ARCHITECTURE_STYLE_GRAPH_KIND, ARCHITECTURE_STYLE_KIND } from './arch-style-kinds';
export { ARCHITECTURE_STARTER_GRAPHS, architectureGraphTemplate, type ArchitectureStarterGraph } from './arch-style-starters';
export {
  ARCHITECTURE_GRAPH_KINDS,
  architectureGraphsOf,
  architectureStylesOf,
  maskWeight,
  paintedMaskAt,
  resolveArchitecturePreset,
  validateArchitectureGraphs,
  type ArchitectureExpansion,
  type ArchitectureGraphLike,
  type ArchitectureMaskBinding,
  type ArchitecturePresetDef,
  type ArchitecturePreview,
  type ArchitectureRoomOpening,
  type ArchitectureRoomPlan,
  type ArchitectureStyleDef,
  type ArchitectureStyleParam,
  type ArchitectureStyles,
  type ResolvedArchitecturePreset,
} from './arch-style';
// Rooms and runs (closed and open outlines): shared walls, storeys, stairs; what a block layer reads of them.
export { ARCHITECTURE_FLOOR_ON_CELLS, ARCHITECTURE_STAIR_SLOTS, ARCHITECTURE_STOREY_HEIGHT_FALLBACK, expandArchitecture, reversedPath } from './arch-rooms';
// Floor plans and furnishing: room programs and furnishing sets (games' graphs), the splitter and the placer.
export {
  FLOOR_PLAN_COUNT_MAX,
  FLOOR_PLAN_GRAPH_NODES,
  FURNISHING_SET_GRAPH_KIND,
  FURNISHING_SET_KIND,
  PROP_PLACES,
  ROOM_PROGRAM_GRAPH_KIND,
  ROOM_PROGRAM_KIND,
  ROOM_STOREYS,
  floorPlanGraphTemplate,
  furnishingSetDef,
  roomProgramDef,
  type FurnishingLightDef,
  type FurnishingPropDef,
  type FurnishingSetDef,
  type PropPlace,
  type RoomProgramDef,
  type RoomStoreys,
  type RoomTypeDef,
} from './arch-plan-kinds';
export { FLOOR_PLAN_TRIES, footprintZones, splitFloorPlan, type FloorPlan, type FloorPlanDoor, type FloorPlanInput, type FloorPlanRoom, type FloorPlanStair, type PlanRect } from './arch-floor-plan';
export { FURNISH_CELL, furnishLights, furnishRoom, facingDir, facingOf, type FurnishedLight, type FurnishedProp, type FurnishOpening, type FurnishPin, type FurnishRoom } from './arch-furnish';
export { buildingFloorPlan, buildingFrontDoors, floorPlanOutlines, propElement } from './arch-building-plan';
export { furnishingLightEntity, furnishingLightId, furnishingLightsOf, withFurnishingLights, type DroppedFurnishingLights, type LightSourceEntity } from './arch-lights';
export { architecturePaintOf, architectureRoomRegions, architectureWallEdges } from './arch-room-grid';
export { buildRoomGraph, portalDistance, portalRect, RoomGraph, roomVisibility, ROOM_OUTSIDE, walkRooms, type GraphPortal, type GraphPortalKind, type GraphRoom, type RoomGraphObject, type RoomVisibility, type ViewProjection } from './arch-portals';
export { chunkLightmapLayout, type ChunkLightmapLayout } from './block-lightmap';
// The instance brush (paint and erase copies of an instance set on a surface).
export {
  INSTANCE_BRUSH_DEFAULTS,
  INSTANCE_BRUSH_LIMITS,
  INSTANCE_BRUSH_REACH,
  StrokeCandidates,
  applyInstanceStroke,
  candidateDrop,
  dropOntoBlockLayers,
  instanceStrokeError,
  strokeCandidates,
  type BrushBlockLayer,
  type BrushVec3,
  type InstanceBrush,
  type InstanceSetSpace,
  type InstanceStroke,
  type InstanceStrokeMode,
  type InstanceStrokeResult,
  type StrokeCandidate,
  type StrokeSurfaceDrop,
  type StrokeSurfaceSample,
} from './instance-brush';
export {
  FLAT_CORNERS,
  anchoredTopAt,
  blockTopAt,
  cellCorners,
  cornerGradientAt,
  cornerHeightAt,
  rotateXZ,
  subdividedGradientAt,
  subdividedHeightAt,
  surfaceBelow,
  type BlockTopSample,
  type CellCorners,
  type SurfaceGrid,
  type SurfaceHit,
} from './block-surface';
// A prop's block footprint: the cells beneath it and the meta edits that move it.
export { footprintCells, footprintEdits, footprintMinCell, footprintPlaces, overLayer, turnedSize, yawQuarterTurns, type FootprintLayer, type FootprintNode, type FootprintProp } from './block-footprint';
// World matrices over a scene's hierarchy (the command layer and the editor read world places alike).
export { compose, decompose, IDENTITY, invert, multiply, placeInWorld, pointInParent, worldMatrix, type HierarchyNode, type Mat4 } from './world-matrix';
export { PNG_DECODE_MAX_PIXELS, decodeBase64, decodePngRgba, encodeBase64, inflateZlib, type DecodedPng, type PngDecodeOptions } from './png-decode';
// The project save schema (save document, slots, sections, settings document).
export {
  SAVE_LIMITS,
  SAVE_META_KEY_RE,
  saveSlotMetaProblem,
  SAVE_SECTIONS,
  saveWorldMode,
  SAVE_THUMBNAIL_DEFAULT,
  SETTINGS_ENGINE_BINDINGS,
  canonicalSaveSchema,
  effectiveField,
  settingsDocumentOf,
  settingsValueFits,
  validateSaveSchema,
  type SaveMigration,
  type SaveSchema,
  type SaveSection,
  type SaveThumbnail,
  type SettingsEngineBinding,
  type SettingsField,
  type SettingsFieldValue,
} from './save-schema';
// The frame-rate cap a game sets (project setting, settings field, UI action, scripts).
export { FRAME_RATE_CAP_CHOICES, FRAME_RATE_CAPS, frameRateCapOf, projectFrameRateCap, type FrameRateCap } from './frame-rate-cap';
export {
  AMBIENT_OCCLUSION_DEFAULT,
  AMBIENT_OCCLUSION_KINDS,
  AMBIENT_OCCLUSION_NEW_PROJECT,
  ambientOcclusionSettingValue,
  AMBIENT_OCCLUSION_SETTING_VALUES,
  ambientOcclusionOf,
  RENDER_SCALE_DEFAULT,
  RENDER_SCALE_MAX,
  RENDER_SCALE_MIN,
  RENDER_SETTINGS_DEFAULT,
  renderScaleOf,
  renderSettingsOf,
  type AmbientOcclusionKind,
  type RenderSettings,
} from './render-settings';
// Quality levels (the project's or the engine's low/medium/high) and how a level changes a scene's post.
export {
  DEFAULT_QUALITY_LEVELS,
  levelPost,
  MSAA_SAMPLE_COUNTS,
  PIXEL_RATIO_CAP_MAX,
  PIXEL_RATIO_CAP_MIN,
  QUALITY_LEVEL_ID_RE,
  QUALITY_POST_EFFECTS,
  qualityLevelOf,
  qualityLevelsOf,
  SHADOW_MAP_SIZES,
  type MsaaSamples,
  type QualityLevelConfig,
  type QualityLevelPost,
} from './quality-levels';
// Dialogue (content.dialogues / speakers / dialogueSettings), its graph kind, expressions and the runtime form.
export {
  DIALOGUE_DEFAULTS,
  DIALOGUE_DOCUMENT_ID,
  DIALOGUE_GRAPH_KIND,
  DIALOGUE_LIMITS,
  applyDialogueEffect,
  canonicalDialogue,
  canonicalDialogueSettings,
  canonicalDialogues,
  canonicalSpeaker,
  canonicalSpeakers,
  compileDialogue,
  dialogueAssetRefs,
  dialogueForRuntime,
  dialogueLineText,
  dialogueNodeProblems,
  dialogueTruthy,
  dialogueUiDocument,
  dialogueValueText,
  evalDialogueExpr,
  newDialogueGraph,
  parseDialogueCondition,
  parseDialogueEffects,
  runtimeDialogueDataProblem,
  validateDialogue,
  validateDialogueReferences,
  validateDialogues,
  validateDialogueSettings,
  validateSpeaker,
  validateSpeakers,
  withDialogueUiDocument,
  type DialogueDocument,
  type DialogueEffect,
  type DialogueEnv,
  type DialogueExpr,
  type DialogueLineText,
  type DialogueSettings,
  type DialogueSpeaker,
  type DialogueValue,
  type RuntimeDialogue,
  type RuntimeDialogueData,
  type RuntimeDialogueNode,
  type RuntimeDialogueOption,
} from './dialogue';
export { codePointLength, parseRichText, richTextVisibleLength, uiValueText, type RichStyle, type RichToken } from './rich-text';
export { UI_DIALOGUE_INPUTS, type UiDialogueInput } from './ui-documents';
// Timelines (sequencer assets).
export {
  TIMELINE_LIMITS,
  TIMELINE_TRACK_TYPES,
  TIMELINE_EASINGS,
  TIMELINE_TARGET_TRACKS,
  validateTimeline,
  validateTimelines,
  validateTimelineReferences,
  timelineRefs,
  canonicalTimeline,
  canonicalTimelines,
} from './timelines';
export type { TimelineAsset, TimelineTrack, TimelineKey, TimelineSlot, TimelineMarker, TimelineTrackType, TimelineEasing, TimelineValue } from './timelines';
export { SIGNAL_DEBUG_COMMAND_NAME, type SignalDebugCommandName } from './debug-command-names';
// The scene rules checked before Play and the export (not per command).
export { playChecks, type PlayCheck } from './play-checks';
export { COLLIDER_PRIMITIVE_TYPES, COLLIDER_SHAPE_TYPES, canonicalShape, colliderShapeParts, colliderShapePoints, spansVolume } from './collider-shapes';
// Collider shapes made from geometry, and a model's collision parts read from its file.
export { boxFromBounds, colliderFromTriangles, convexFromPoints, convexHull2, hullPoints, polygonFromPoints, roundMm, type GeometryCollider } from './collider-geometry';
export { MODEL_COLLIDER_KINDS, collisionPartPolygons, sceneColliderPoints, validateModelColliderTable, modelColliderShape, modelCollisionParts, readModelGeometry, type ModelColliderKind, type ModelColliderTable, type ModelCollisionPart, type ModelGeometry, type ModelGeometryPrimitive } from './model-collision';
