/**
 * @thirdlight/project-model — public surface: types, parse*, validate*,
 * normalize*, serializeCanonical, ERROR_CODES, KNOWN_VERSIONS.
 *
 * Only storage v4 projects load (`validateProjectV4`); a v3 project is read
 * (`validateEnvelopeV3`/`validateProjectV3`) and upgraded on open
 * (`migrateProjectV3ToV4`). Shared component rules live in `components.ts`.
 * Strict byte parsing with duplicate-key rejection, total value validation,
 * normalization to the canonical form and canonical byte serialization.
 *
 * Pure data and logic: no I/O, no three.js, no Node built-ins — the leaf
 * unit of the node-side graph. All entry points are
 * pure and total: same input → same result; malformed data yields error
 * results, never thrown exceptions.
 */

export {
  ERROR_CODES,
  KNOWN_VERSIONS,
  SCHEMA_VERSIONS_BY_DOCUMENT,
  type EnvelopeV3Error,
  type EnvelopeV3ErrorCode,
  type ErrorCode,
  type LimitName,
  type ModelError,
  type ModelErrorV2,
  type ModelErrorV3,
  type ModelResult,
  type ModelResultV2,
  type ModelResultV3,
  type SerializeResult,
} from './errors';

export type {
  BoxComponent,
  BoxMaterial,
  CameraComponent,
  Manifest,
  Quat,
  SceneRef,
  TransformComponent,
  Vec3,
} from './types';

export type {
  AssetMetrics,
  AssetRecord,
  AssetVersion,
  ConvertedFrom,
  PackedChannel,
  PackedFrom,
  BehaviorComponent,
  BehaviorRecord,
  BehaviorSourceRecord,
  BehaviorTrust,
  CapturedAsset,
  CapturedContent,
  ColliderBoxShape,
  ColliderComponent,
  ColliderPolygonShape,
  ColliderSphereShape,
  ColliderCapsuleShape,
  ColliderConvexShape,
  ColliderMeshShape,
  ColliderShape,
  ContentCatalog,
  ControllerCapsule,
  ControllerComponent,
  DeclaredProperty,
  EntityComponentsV2,
  GameplaySettings,
  ImportRecipe,
  ModelAssetRef,
  ModelComponent,
  PrefabComponentsV2,
  PrefabDefinition,
  PrefabEntity,
  PrefabProvenanceComponent,
  PrefabComponentsV4Extra,
  PropertyBounds,
  PropertyDeclaration,
  PropertyType,
  PropertyValue,
  PropertyVisibility,
  SettingsMap,
  SettingsValue,
  TrustEntry,
} from './types-v2';

// The character capsule (default, limits, resolved form).
export { CAPSULE_LIMITS, COLLIDER_3D_LIMITS, COLLIDER_3D_SHAPES, CONTROLLER_FIELDS, CONTROLLER_TUNING_FIELDS, CONTROLLER_TUNING_LIMITS, DEFAULT_CONTROLLER_CAPSULE, DEFAULT_CONTROLLER_TUNING, controllerCapsuleOf, controllerCapsuleOffsetZ, controllerTuningOf, CHARACTER_3D_LIMITS, CONTROLLER_3D_FIELDS, DEFAULT_CHARACTER_3D, character3DSettingsOf, CHARACTER_MOVE_FRAMES, type CharacterMoveFrame, CONTROLLER_ACTION_FIELDS, CONTROLLER_ACTION_DEFAULTS, controllerActionsOf, type Character3DSettings, CONTROLLER_MOVEMENT_FIELDS, CONTROLLER_MOVEMENT_LIMITS, DEFAULT_CONTROLLER_MOVEMENT, controllerMovementOf, type ControllerMovementSettings } from './components';
// Collision layers.
export { DEFAULT_COLLISION_LAYER, MAX_COLLISION_LAYERS, validateCollisionLayers } from './components';
export { parseDocumentBytes, type ByteParse } from './parse-bytes';
export { parseEnvelopeV3, parseManifest, parseSceneV3 } from './parse-api';

export { validateManifest, normalizeManifest, boundedFound } from './validate';
export * from './limits';

export {
  M2_SETTINGS_KEYS,
  RENDERING_SETTINGS_GROUP,
  AUDIO_VOICE_CAP,
  PHYSICS_DIMENSIONS,
  audioSpatialOf,
  depthBufferOf,
  instanceChunkSizeOf,
  physicsDimensionOf,
  type PhysicsDimension,
  MAX_SOURCE_PATH_LENGTH,
  MAX_CONVERTED_SOURCE_BYTES,
  M2_GLTF_EXTENSION_ALLOWLIST,
  isValidSourcePath,
  normalizeContentV3,
  resolveGameplaySettings,
  validateContentV3,
  validateGameConfig,
  validateTagRegistry,
  TAG_NAME_RE,
  type SettingsKeySpec,
} from './content';

// The explicit v3 model surface: the versioned scene/content entry points,
// the v3 registry/limits/preset constants, the v3 types and the
// component-level validators.
export {
  AUDIO_DECODE_ON_LOAD_BELOW_MS,
  AUDIO_FORMATS,
  AUDIO_LOAD_TYPES,
  AUDIO_PIPELINE_NAME,
  AUDIO_PIPELINE_VERSION,
  AUDIO_STREAM_ABOVE_MS,
  audioLoadOf,
  audioPlaybackGaps,
  audioSummaryOf,
  defaultAudioLoadType,
  upgradeAudioAssets,
  upgradeAudioRecord,
  type AudioFormat,
  type AudioLoadSettings,
  type AudioLoadType,
  type AudioMetrics,
  type AudioRecipe,
  type AudioSummary,
} from './audio-assets';
export {
  TEXTURE_BUDGET_DEFAULT_MB,
  TEXTURE_BUDGET_MAX_MB,
  TEXTURE_BUDGET_MIN_MB,
  TEXTURE_STREAMING_DEFAULT_ABOVE_PX,
  TEXTURE_STREAM_TAIL_PX,
  textureBudgetBytesOf,
  textureHasStreamableChain,
  textureStreamingOf,
} from './texture-streaming';
export {
  buildKtx2Subset,
  isKtx2Bytes,
  ktx2IndexBytes,
  ktx2LevelSize,
  planKtx2Parts,
  readKtx2Layout,
  type Ktx2Layout,
  type Ktx2LayoutResult,
  type Ktx2Level,
  type Ktx2Part,
  type Ktx2Range,
} from './ktx2-levels';
export {
  normalizeSceneV3,
  validateLightComponent,
  validateModelAnimationComponent,
  validatePlayerSpawnComponent,
  validateSceneV3,
  validateSurfaceComponent,
} from './scene-v3';
export {
  SCENE_LIMITS_V3,
  SURFACE_PRESETS,
  SURFACE_PRESET_NAMES,
  type SurfacePresetName,
  V3_REGISTRY,
  isFolderEntity,
  MAX_TAGS,
  type TagDefinition,
  type EntityFlagsV3,
  type FolderComponent,
  type FolderEntityV3,
  type ResolvedSceneV3,
  type SceneEntityV3,
  type AnimationRoleBinding,
  type AssetKind,
  type AssetMetricsV3,
  type AssetRecordV3,
  type AssetVersionV3,
  type AuthoringEnvelopeV3,
  type ComponentV3,
  type ContentCatalogV3,
  type EntityComponentsV3,
  type EntityV3,
  type GltfGlbRecipeV3,
  type ImportRecipeV3,
  type LightComponent,
  type ModelAnimationComponent,
  type PlayerSpawnComponent,
  type SceneV3,
  type SurfaceComponent,
} from './types-v3';
export {
  effectiveEntityFlags,
  nearestObjectAncestor,
  resolveSceneHierarchy,
  type EffectiveEntityFlags,
} from './hierarchy-v3';
export {
  normalizeEnvelopeV3,
  validateEnvelopeV3,
  validateProjectV3,
  composeContentChecks,
  type EnvelopeV3Load,
} from './project-v3';

export { captureContent, collectAssetRefsV3 } from './capture';

// The pure runtime-content manifest capture
// plus the canonical/digest helpers the export closure needs. Additive public
// surface recorded as contract-change request C36-2 (docs/handoffs/36.md).
export {
  BUILD_OPTIONS_RECORD,
  MANIFEST_KEYS,
  M2_ENGINE_PINS,
  M2_KNOWN_MODULE_IDS,
  M2_MODULE_PACKAGES,
  RUNTIME_CONTENT_MANIFEST_MAX_BYTES,
  RUNTIME_CONTENT_MANIFEST_VERSION,
  RUNTIME_CONTENT_TYPE,
  buildOptionsRecordBytes,
  captureManifest,
  capturedViewDigest,
  digestBytes,
  digestEmittedClosure,
  manifestBuildIdInput,
  recipeDigestOf,
  requiredModuleIds,
  versionFactsDigest,
  type CaptureManifestInput,
  type CaptureManifestResult,
  type EmittedArtifactDigest,
  type ManifestAssetInput,
  type ManifestBehaviorInput,
  type ManifestError,
  type RuntimeContentManifest,
} from './manifest';
export { canonicalJsonText, sha256Hex, sha256HexOfText,
  sha256HexAsync, sha256Hex as sha256HexBytes } from './sha256';

// The pure manifest v2 derivation — the immutable runtime-content identity,
// the captured v3 content view, the media identity and the strict v2 reader
// + version-compat rule.
export {
  blockDigest,
  captureContentViewV3,
  captureManifestV2,
  M3_ENGINE_PINS,
  M3_KNOWN_MODULE_IDS,
  M3_MODULE_PACKAGES,
  M3_RECIPE_VERSIONS,
  M3_SETTINGS_KEYS,
  MANIFEST_KEYS_V2,
  type ManifestSceneRow,
  type ManifestLibraryRow,
  manifestBuildIdInputV2,
  manifestVersionCompat,
  mediaProfileDigest,
  resolveMediaIdentityV3,
  RUNTIME_CONTENT_MANIFEST_VERSION_4,
  // The manifest's content files.
  MANIFEST_CONTENT_FILE_KEYS,
  MANIFEST_CONTENT_FILE_MAX_BYTES,
  type ManifestContentFileKey,
  type ManifestContentFileRow,
  type ManifestContentFile,
  type ExpandedRuntimeContentManifest,
  validateManifestV2,
  type CapturedAssetV3,
  type CapturedContentViewV3,
  type CaptureManifestV2Input,
  type CaptureManifestV2Result,
  type ManifestAssetInputV2,
  type ManifestMipPart,
  type ManifestErrorV2,
  type MediaAnimationRow,
  type MediaBlock,
  type RuntimeContentManifestV2,
  type ValidateManifestV2Options,
  type ValidateManifestV2Result,
} from './manifest-v2';
// What scenes, models and the project-wide blocks need of the shipped assets (the catalog's dependency lists).
export { dependencyTables, scanDependencies, type DependencyScanTables } from './catalog-dependencies';
export { assetUsers, projectWideRoots, startDrawSet, type MissingAssetFile, type MissingFileUser, type MissingPlayFile } from './missing-files';
// The v5 manifest (identity, start, the catalog's location) and its catalog files.
export {
  captureManifestV5,
  catalogBlockProblem,
  catalogEntriesProblem,
  catalogRootProblem,
  CATALOG_BLOCK_KEYS,
  CATALOG_PART_BYTES,
  CATALOG_SHARD_ENTRIES,
  joinCatalogParts,
  manifestBuildIdInputV5,
  restampManifestV5,
  MANIFEST_KEYS_V5,
  readRuntimeContentSync,
  RUNTIME_CONTENT_MANIFEST_VERSION_5,
  validateManifestV5,
  type CatalogBlockKey,
  type CatalogBlockRow,
  type CatalogEntry,
  type CatalogFile,
  type CatalogFileRef,
  type CatalogRootV5,
  type CatalogSceneRow,
  type CatalogShardRow,
  type CaptureManifestV5Input,
  type CaptureManifestV5Result,
  type CaptureSceneV5,
  type ExpandedRuntimeContent,
  type ManifestAssetInputV5,
  type RuntimeContentManifestV5,
} from './manifest-v5';

export { serializeCanonical } from './normalize';

// The engine module registry + the declared-dependency resolver.
export {
  BEHAVIOR_PACKAGE_MODULES,
  ENGINE_MODULES,
  ENGINE_MODULE_IDS,
  resolveRequiredModules,
  type EngineModule,
  type ResolveModulesInput,
  type ResolveModulesResult,
  type UnresolvedModule,
} from './modules';

// v4 projects — several scenes, one file each.
export {
  composeV4,
  composeSceneV4,
  migrateProjectV3ToV4,
  validateManifestV2Project,
  validateProjectV4,
  MIGRATED_SCENE_NAME,
  type MigrationV4Result,
  type ProjectManifestV2,
  type ProjectV4,
} from './project-v4';
// The project format after the engine/game separation (the loader's upgrade).
export {
  PROJECT_SCHEMA_VERSION,
  PROJECT_SCHEMA_VERSION_UPGRADED,
  PROJECT_SCHEMA_VERSION_V24,
  PROJECT_SCHEMA_VERSION_V25,
  PROJECT_SCHEMA_VERSION_PROJECT_LOOK,
  PROJECT_SCHEMA_VERSION_SCENE_CAMERA,
  isUpgradedProjectSchemaVersion,
  REMOVED_FROM_ENGINE,
  REMOVED_COMPONENTS,
  removedComponentMessage,
  isRemovedComponent,
  upgradeProjectDocsV24,
  type UpgradeV24Result,
} from './upgrade-v24';
// project.json schemaVersion 4 (a 3 is upgraded on load without changing a document).
export { upgradeProjectDocsV25, type UpgradeV25Result } from './upgrade-v25';
// project.json schemaVersion 6 (a 5's project-wide look is copied into every scene on load).
export { upgradeSceneEnvironments, type UpgradeSceneEnvironmentResult } from './upgrade-scene-environment';
export { upgradeSceneModel, sceneCameraAsShot, sceneCamerasAsShots, type UpgradeSceneModelResult } from './upgrade-scene-model';
// The materials a game uses (the manifest leaves the others out).
export { materialsInUse, type MaterialUseInput } from './material-use';
// The assigned entity ids (at least six digits; four-digit ids still load).
export { ENTITY_ID_DIGITS, ENTITY_ID_MAX, entityIdAt, nextFreeEntityIdOf } from './entity-ids';
export { validateSceneV4, validateMergedSceneV4, validateInstancesComponent, DIRECTIONAL_SHADOW_DEFAULTS, DIRECTIONAL_SHADOW_LIMITS, ENTITY_FLAGS, MAX_ENTITIES_V4, V4_REGISTRY } from './scene-v3';
export { validateContentV4, isNormalizedContent, ENGINE_TIMING_DEFAULTS } from './content';
// Texture arrays and packed textures.
export { arrayTextureIds, TEXTURE_ARRAY_KIND, MAX_TEXTURE_LAYERS, KTX2_ENCODINGS, canonicalLabels, isAssetLabel, type Ktx2Encoding } from './content';
// Addresses and labels: what a script may load by name (assets on their records, resources beside theirs).
export { canonicalLoadable, ENV_PRESETS_LIST, isAddress, isLoadable, liveLoadable, loadableAssetIds, loadableResourceIds, loadableRows, loadableRowsProblem, RESOURCE_KIND_TABLE, resourceKindDef, resourceRecordsOf, type LoadableEntry, type LoadableRow, type ResourceKindDef } from './loadable';
// Prefabs spawned into a running game (the snapshot/manifest carry them).
export { PREFAB_V4_COMPONENTS, canonicalPrefabs, validatePrefabDefinitions } from './content';
export { declarationBytes } from './content-behaviors';
export {
  INSTANCE_FLOATS,
  MAX_INSTANCES,
  type ContentCatalogV4,
  type SceneIndexEntry,
  type InstancesComponent,
  type SceneV4,
} from './types-v3';
// Gameplay building blocks.
export {
  BLOCK_COMPONENT_NAMES,
  BLOCK_COMPONENTS,
  // The blocks' tuning defaults and ranges.
  BLOCK_DEFAULTS,
  BLOCK_TUNING_LIMITS,
  MOVER_MODES,
  SWITCH_MODES,
  // Trigger shapes and modes.
  TRIGGER_MODES,
  TRIGGER_RADIUS,
  TRIGGER_SHAPES,
  TRIGGER_HEIGHT,
  // The generic primitives.
  PATROL_MODES,
  HITBOX_SHAPES,
  PRIMITIVE_DEFAULTS,
  PRIMITIVE_LIMITS,
  type CollectibleComponent,
  // Scene transitions, switch actions, face-velocity models.
  FACE_MOVEMENT_MODES,
  MAX_TRANSITION_UNLOADS,
  MAX_TRANSITION_FADE,
  SWITCH_DEFAULT_ACTION,
  type SceneTransitionAction,
  type PatrolComponent,
  type HitboxComponent,
  // Climb volumes and gravity bodies.
  GRAVITY_SCALE,
  type ClimbVolumeComponent,
  type GravityComponent,
  type BlockComponentName,
  type AudioSourceComponent,
  type FaceMovementComponent,
  type HealthComponent,
  type MoverComponent,
  type SwitchComponent,
  type TriggerComponent,
} from './blocks';
// The one counter-name rule (scripts, collectibles and the save loader).
export { COUNTER_NAME_RE, COUNTER_NAME_RULE, isCounterName } from './counter-names';
// The generic node-graph model and the registered graph kinds.
export {
  applyGraphOps,
  canonicalGraphData,
  canonicalGraphDocuments,
  findCycle,
  GRAPH_AUTO_TYPE,
  GRAPH_ITEM_ID_RE,
  graphAssetRefs,
  graphDocumentsContext,
  graphInterface,
  resolveGraphPorts,
  repeatedPorts,
  repeatItems,
  staticNodePorts,
  GRAPH_LIMITS,
  GRAPH_CURVE_LIMITS,
  curveValueError,
  gradientValueError,
  GRAPH_OP_NAMES,
  nodeDef,
  nodeFieldValue,
  nodePorts,
  portCompatibility,
  validateGraphData,
  validateGraphDocument,
  validateGraphDocuments,
  validateGraphOps,
  wouldCycle,
  type GraphComment,
  type GraphContext,
  type GraphConversion,
  type GraphInterfaceDef,
  type GraphNodePorts,
  type GraphPortTypeRule,
  type GraphPortRepeat,
  type GraphData,
  type GraphDocument,
  type GraphEdge,
  type GraphFieldDef,
  type GraphGroup,
  type GraphKindDef,
  type GraphNode,
  type GraphNodeDef,
  type GraphOp,
  type GraphOpsResult,
  type GraphPoint,
  type GraphPortDef,
  type GraphPortRef,
  type GraphPortType,
  type GraphValue,
} from './graph';
export { ANIMATOR_BLEND_GRAPH_KIND, ANIMATOR_GRAPH_KIND, ANIMATOR_LAYER_GRAPH_KIND, GRAPH_KINDS, TEST_GRAPH_KIND } from './graph-kinds';
// Visual scripts (the `behavior` graph kinds, their node catalogue and compile checks).
export {
  BEHAVIOR_API_NODES,
  CALLBACK_EVENT_NODES,
  BEHAVIOR_DATA_TYPES,
  BEHAVIOR_FUNCTION_GRAPH_KIND,
  BEHAVIOR_FUNCTION_ID_RE,
  BEHAVIOR_FUNCTION_KIND,
  BEHAVIOR_GRAPH_KIND,
  BEHAVIOR_GRAPH_LIMITS,
  BEHAVIOR_LIBRARY_GRAPH_KIND,
  BEHAVIOR_LIBRARY_KIND,
  BEHAVIOR_VALUE_TYPES,
  BEHAVIOR_VARIABLE_KINDS,
  BEHAVIOR_VARIABLE_NAME_RE,
  DATA_TYPE_DEFAULT,
  REQUIRED_CORE_FIELDS,
  VARIABLE_PORT_TYPE,
  VARIABLE_PROPERTY_TYPE,
  axesOptions,
  behaviorApiSpec,
  behaviorFunctionInterface,
  behaviorGraphContext,
  behaviorGraphDeclaration,
  behaviorNodePhases,
  behaviorOwnedTransforms,
  behaviorScriptGraphs,
  calleeScope,
  checkBehaviorGraph,
  enumOptions,
  eventPhase,
  isVariableAccess,
  parseVariableValue,
  scopedNodeId,
  variableLabel,
  variableNodesOf,
  variableProperty,
  variableTypeOf,
  variableVisibility,
  type BehaviorFunctionRecord,
  type BehaviorGraphProblem,
  type BehaviorScriptEnv,
  type BehaviorScriptGraph,
  type BehaviorValueType,
  type BehaviorVariableKind,
} from './behavior-graph';
export { BEHAVIOR_API_SKIPPED } from './behavior-api.generated';
export type { BehaviorApiArg, BehaviorApiNodeSpec, BehaviorApiOutput, BehaviorApiStep, BehaviorApiValue, BehaviorDataType } from './behavior-api';
// Shared script libraries (content.scriptLibraries) and behavior library pins.
export {
  SCRIPT_LIBRARY_ENTRY,
  SCRIPT_LIBRARY_IMPORT_PREFIX,
  SCRIPT_LIBRARY_LIMITS,
  applyScriptLibraryPatch,
  canonicalScriptLibraries,
  canonicalScriptLibrary,
  scriptLibraryContainerText,
  scriptLibraryDependents,
  scriptLibraryDigest,
  scriptLibraryPathProblem,
  scriptLibrarySetKey,
  validateLibraryPins,
  validateScriptLibraries,
  validateScriptLibrary,
} from './script-libraries';
export type { BehaviorLibraryPin, ScriptLibrary, ScriptLibraryFile, ScriptLibraryPatch } from './script-libraries';
// Project UI documents and themes (content.uiDocuments / uiThemes, shell.screens).
export {
  UI_EASINGS,
  UI_ENGINE_ACTIONS,
  UI_DEPRECATED_ENGINE_ACTIONS,
  UI_GENERIC_FONTS,
  UI_LIMITS,
  UI_SAVE_SLOTS,
  UI_SCALE_MODES,
  UI_SOUND_EVENTS,
  UI_SHELL_SCREENS,
  UI_TWEEN_KINDS,
  UI_WIDGET_TYPES,
  canonicalUiDocument,
  canonicalUiDocuments,
  canonicalUiTheme,
  canonicalUiThemes,
  uiAssetRefs,
  uiBindPathProblem,
  uiDocumentsForRuntime,
  uiItemKeyProblem,
  uiTextPlaceholders,
  validateUiDocument,
  validateUiDocuments,
  validateUiReferences,
  validateUiStyle,
  validateUiTheme,
  validateUiThemes,
} from './ui-documents';
export type { RuntimeUiDocumentRow, UiAction, UiBindable, UiBinding, UiColor, UiDocument, UiDocumentRefs, UiEasing, UiEngineAction, UiIcon, UiScalar, UiScaleMode, UiSounds, UiStyle, UiStyleValues, UiTheme, UiTween, UiTweenKind, UiWidget, UiWidgetType, UiWorldAnchor } from './ui-documents';
export { UI_DESCRIPTORS, type UiDescriptors } from './ui-descriptors';
// Visual effects (content.effects, the effect component) and the effect graph kind.
export {
  EFFECT_ATTRIBUTES,
  EFFECT_ATTRIBUTE_TYPES,
  EFFECT_BLEND_MODES,
  EFFECT_CONTEXTS,
  EFFECT_CONTEXT_FLOWS,
  EFFECT_CONTEXT_LAYOUT,
  EFFECT_EVENTS,
  EFFECT_GRAPH_KIND,
  EFFECT_GRAPH_LIMITS,
  EFFECT_LIGHT_LIMIT,
  EFFECT_SHADING,
  EFFECT_VALUE_TYPES,
  effectFieldDefault,
  newEffectSystemGraph,
  type EffectContext,
  type EffectValueType,
} from './effect-graph-kinds';
export {
  EFFECT_DEFAULTS,
  EFFECT_LIMITS,
  EFFECT_PARAMETER_TYPES,
  canonicalEffect,
  canonicalEffectComponent,
  canonicalEffects,
  effectAssetRefs,
  effectComponentErrors,
  effectMaterialRefs,
  effectsForRuntime,
  effectGraphContext,
  effectParameterPortType,
  effectParameterValueError,
  effectSystemOwnerId,
  parseEffectSystemOwnerId,
  validateEffect,
  validateEffectComponent,
  validateEffectParameters,
  validateEffects,
  type EffectComponent,
  type EffectDef,
  type EffectParameter,
  type EffectParameterType,
  type EffectSystem,
} from './effects';
// The camera framework's data (virtual cameras and camera paths).
export {
  CAMERA_BLENDS,
  CAMERA_PATH_FIELDS,
  CAMERA_PATH_LIMITS,
  CAMERA_RAIL_MODES,
  VIRTUAL_CAMERA_DEFAULTS,
  VIEW_LENS_DEFAULTS,
  DEFAULT_VIEW_POSE,
  DEFAULT_VIEW_ID,
  viewLensOf,
  VIRTUAL_CAMERA_FIELDS,
  VIRTUAL_CAMERA_LIMITS,
  VIRTUAL_CAMERA_RIGS,
  canonicalCameraPath,
  canonicalVirtualCamera,
  validateCameraPathComponent,
  validateVirtualCameraComponent,
  CAMERA_REGION_DEFAULTS,
  CAMERA_REGION_FIELDS,
  CAMERA_REGION_LIMITS,
  canonicalCameraRegion,
  validateCameraRegionComponent,
  type CameraRegionComponent,
  type CameraBlendStyle,
  type CameraPathComponent,
  type CameraRailMode,
  type VirtualCameraComponent,
  type VirtualCameraRig,
} from './cameras';
// Sockets (an entity on a node of another entity's model) and model rigs as simulation data.
export {
  SOCKET_ATTACH_CONFLICTS,
  SOCKET_ATTACH_FIELDS,
  SOCKET_ATTACH_LIMITS,
  canonicalSocketAttach,
  validateSocketAttachComponent,
  type SocketAttachComponent,
} from './sockets';
export {
  MODEL_RIG_LIMITS,
  quatFromRotation,
  readModelRig,
  rigNodeNames,
  sanitizeRigNodeName,
  validateModelRig,
  type ModelRig,
  type ModelRigChannel,
  type ModelRigClip,
  type ModelRigNode,
  type RigInterpolation,
  type RigPath,
} from './model-rig';
// The material node catalogue (material graphs and material functions).
export { MATERIAL_BUILTIN_SOURCES, MATERIAL_DATA_MAX, MATERIAL_FUNCTION_GRAPH_KIND, MATERIAL_GRAPH_KIND, MATERIAL_PARAMETER_TYPES, MATERIAL_VALUE_TYPES, type MaterialParameterType } from './material-graph-kinds';
// An animator controller's layers and blend trees as graphs (owner kind `animator`).
export { animatorGraphOf, animatorTransitionPairs, applyAnimatorGraph, parseAnimatorOwnerId, type AnimatorGraphWrite, type AnimatorOwnerTarget } from './animator-graph';
// Input actions.
export {
  canonicalInput,
  DEFAULT_INPUT,
  DEFAULT_INPUT_3D,
  defaultInputFor,
  INPUT_ACTION_TYPES,
  INPUT_MAPS,
  MAX_INPUT_ACTIONS,
  validateInput,
  type InputAction,
  type InputActionType,
  type InputBinding,
  type InputConfig,
  // Pointer bindings and the cursor per map.
  CURSOR_MODES,
  POINTER_AXES,
  POINTER_BUTTONS,
  type CursorMode,
  type PointerAxisName,
  type PointerButtonName,
  // The project's own input maps.
  MAX_INPUT_MAPS,
  projectInputMaps,
  type InputMapName,
  // The hold modifier and the project's glyph images.
  GAMEPAD_FAMILIES,
  GLYPH_KEY_RE,
  HOLD_BINDING_KINDS,
  INPUT_HOLD_MAX,
  INPUT_HOLD_MIN,
  MAX_INPUT_GLYPHS,
} from './input';
// Game modes (content.modes), behavior groups and the behaviorGroup component.
export {
  MODE_BLENDS,
  MODE_DEFAULTS,
  MODE_LIMITS,
  MODE_NAME_RE,
  MODE_PHYSICS,
  MODE_UNGROUPED,
  behaviorGroupErrors,
  canonicalBehaviorGroup,
  canonicalMode,
  canonicalModes,
  modesForRuntime,
  validateBehaviorGroupComponent,
  validateBehaviorGroups,
  validateMode,
  validateModeReferences,
  validateModes,
  validateModeTransition,
} from './modes';
export type { BehaviorGroupComponent, GameMode, ModeBlend, ModePhysics, ModeTransition, ModeUngrouped, RuntimeModes } from './modes';
// The event → cue table.
export { ENGINE_EVENT_TYPES, EVENT_CUE_BUSES, EVENT_CUE_FIELDS, EVENT_CUE_LIMITS, EVENT_CUE_SOURCES, canonicalEventCue, canonicalEventCues, validateEventCue, validateEventCueReferences, validateEventCues, type EventCue } from './event-cues';
export { SHELL_FIELDS, SHELL_LIMITS, SHELL_SCREENS, canonicalShell, validateShell, validateShellReferences, type GameShell, type ShellScene, type ShellScreen } from './shell';
// The old modelAnimation profile becomes an animator controller on open.
export { glbClipDurations, LEGACY_CROSSFADE_SECONDS, LEGACY_RUN_SPEED_EPS, migrateModelAnimations, type ClipDurationOf, type ModelAnimationMigration } from './animator-migrate';
// Animator controllers.
export {
  ANIMATOR_CONDITION_OPS,
  ANIMATOR_PARAMETER_TYPES,
  ANIMATOR_RESERVED_GRAPH_ID_RE,
  animatorAssetIds,
  animatorsForRuntime,
  animatorStates,
  canonicalAnimatorController,
  canonicalAnimators,
  MAX_ANIMATOR_LAYERS,
  MAX_LAYER_MASK,
  validateAnimatorComponent,
  validateAnimatorController,
  validateAnimators,
  type AnimatorClipRef,
  type AnimatorComponent,
  type AnimatorCondition,
  type AnimatorConditionOp,
  type AnimatorController,
  type AnimatorEvent,
  type AnimatorLayer,
  type AnimatorLayout,
  type AnimatorMotion,
  type AnimatorParameter,
  type AnimatorParameterType,
  type AnimatorState,
  type AnimatorTransition,
} from './animator';
// Baked lighting.
export {
  canonicalLighting,
  LIGHTMAP_SOURCES,
  MAX_LIGHTMAP_ATLASES,
  MAX_LIGHTMAP_ENTRIES,
  MAX_BAKED_LIGHTS,
  validateLighting,
  validateLightingBake,
  type LightingBake,
  type LightingEntry,
  type LightingMap,
} from './lighting';
// Materials, material mappings and the environment (a scene's look, the project's quality and presets).
export {
  canonicalEnvironment,
  canonicalMaterialMapping,
  canonicalMaterials,
  DEFAULT_WIND,
  MATERIAL_PARAMS,
  MATERIAL_SHADERS,
  MATERIAL_SLOT_ALL,
  MATERIAL_TEXTURE_SLOTS,
  materialParamError,
  // Graph materials (exposed parameters, the graph, the runtime view).
  canonicalMaterialParameters,
  MATERIAL_PARAMETER_KEY_RE,
  materialGraphContext,
  materialParameterPortType,
  materialParameterValueError,
  materialsForRuntime,
  materialFunctionsForRuntime,
  materialTextureRefs,
  graphForRuntime,
  MAX_MATERIAL_PARAMETERS,
  validateMaterialGraph,
  validateMaterialParameters,
  canonicalMaterialParams,
  materialOverrideErrors,
  validateMaterialParamsComponent,
  type MaterialParamsComponent,
  type MaterialParameter,
  type MaterialParameterValue,
  MAX_MATERIAL_SLOTS,
  validateEnvironment,
  validateMaterialMapping,
  validateMaterials,
  // Material instances.
  MAX_MATERIAL_INSTANCE_DEPTH,
  resolveMaterial,
  resolveMaterialInstances,
  validateMaterialInstances,
  validateFogVolumeComponent,
  MAX_FOG_VOLUMES,
  canonicalSceneEnvironment,
  environmentTextureRefs,
  SCENE_ENVIRONMENT_FIELDS,
  sceneEnvironmentIsEmpty,
  validateSceneEnvironment,
  type SceneEnvironment,
  type EnvironmentConfig,
  type FogConfig,
  type FogVolumeComponent,
  type PostConfig,
  type SkyConfig,
  type MaterialDef,
  type MaterialParamType,
  type MaterialParamValue,
  type MaterialShader,
  type WindConfig,
} from './materials';

// Environment presets (named looks scripts switch or blend to).
export {
  ENVIRONMENT_LIGHT_TYPES,
  ENVIRONMENT_PRESET_LIMITS,
  canonicalEnvironmentPresets,
  environmentPresetTextureRefs,
  validateEnvironmentPatch,
  validateEnvironmentPresets,
  type EnvironmentLightType,
  type EnvironmentLookParts,
  type EnvironmentPreset,
  type EnvironmentPresetLight,
  type EnvironmentPresetLightmap,
} from './environment-presets';

// The component and content descriptor registry (pure data).
export {
  ASSET_KINDS,
  COMPONENT_ICONS,
  DESCRIPTORS,
  HANDLE_KINDS,
  HANDLE_ROLES,
  type AssetRefFieldDescriptor,
  type BoolFieldDescriptor,
  type ColorFieldDescriptor,
  type ComponentAdd,
  type ComponentDescriptor,
  type ComponentIcon,
  type CreateEntryDescriptor,
  type ComponentRelation,
  type ComponentsFieldDescriptor,
  type ContentBlockDescriptor,
  type DescriptorAssetKind,
  type DescriptorJson,
  type DescriptorRefTarget,
  type DescriptorRegistry,
  type DescriptorScalar,
  type DescriptorStringFormat,
  type DescriptorUnit,
  type EntityRefFieldDescriptor,
  type EnumFieldDescriptor,
  type EnumOption,
  type FieldCondition,
  type FieldDescriptor,
  type FieldType,
  type HandleDescriptor,
  type HandleKind,
  type IntFieldDescriptor,
  type JsonFieldDescriptor,
  type ListFieldDescriptor,
  type MapFieldDescriptor,
  type NumberFieldDescriptor,
  type ObjectFieldDescriptor,
  type QuatFieldDescriptor,
  type RefFieldDescriptor,
  type SceneRefFieldDescriptor,
  type SignalFieldDescriptor,
  type StringFieldDescriptor,
  type VecFieldDescriptor,
} from './descriptors';

// Generic component access for scripts (ctx.entity): the table and the write check.
export {
  SCRIPT_ACCESS_SCHEMA_VERSION,
  SCRIPT_OBJECT_COMPONENT,
  checkScriptPatch,
  scriptAccessTable,
  scriptComponentAccess,
  scriptSnapshot,
  type ScriptAccessTable,
  type ScriptComponentAccess,
  type ScriptPatchResult,
  type ScriptWriteCode,
  type ScriptWriteProblem,
} from './script-fields';

// Block layers — data model, grid, edits, meshing, PNG heightmaps.
export {
  BLOCK_LAYER_DEFAULT,
  BLOCK_LIMITS,
  BLOCK_SHAPES,
  CELL_FIELD_KEY_RE,
  CELL_FIELD_TYPES,
  CHUNK_SIZE,
  REGION_ID_RE,
  blockCellKey,
  blockTypeSolid,
  canonicalBlockCell,
  canonicalBlockChunk,
  canonicalBlockLayerComponent,
  canonicalBlockFootprint,
  validateBlockFootprintComponent,
  BLOCK_FOOTPRINT_MAX,
  type BlockFootprintComponent,
  canonicalBlockStamp,
  canonicalBlockStamps,
  canonicalBlockType,
  canonicalBlockTypes,
  canonicalCellFields,
  canonicalRuns,
  canonicalSceneBlocks,
  cellFieldDefault,
  cellFieldValueError,
  composeBlockContent,
  composeBlockLayers,
  rotatedFootprint,
  blockTypeSlopes,
  BLOCK_CORNER_STEPS,
  BLOCK_CORNER_MAX,
  BLOCK_LAYER_FIELDS,
  BLOCK_MAX_SLOPE_RANGE,
  BLOCK_SMOOTH_ANGLE_RANGE,
  BLOCK_TOP_SUBDIVISIONS,
  validateBlockCell,
  validateBlockLayerComponent,
  validateBlockRegion,
  validateBlockStamp,
  validateBlockStamps,
  validateBlockType,
  validateBlockTypes,
  validateCellFields,
  validateSceneBlocks,
  type BlockCell,
  type BlockChunk,
  type BlockContentView,
  type BlockLayerComponent,
  type BlockLayerData,
  type BlockRegion,
  type BlockShape,
  type BlockStamp,
  type BlockType,
  type BlockVariant,
  type CellField,
  type CellFieldType,
  type CellMetaValue,
} from './block-layers';
export {
  BLOCK_EDIT_KINDS,
  BLOCK_EDIT_MAX_CELLS,
  BLOCK_EDIT_MAX_EDITS,
  SURFACE_EDIT_MAX_COLUMNS,
  blockEditsShapeError,
  BlockGrid,
  applyBlockEdits,
  autoVariant,
  boxContains,
  cellCenter,
  cellKeyOf,
  cellOfKey,
  chunkKeyOf,
  compareChunkKeys,
  effectiveCellMeta,
  pickCell,
  regionCells,
  regionContains,
  subtractBox,
  worldToCell,
  type BlockEdit,
  type BlockEditContext,
  type BlockEditResult,
  type BlockPick,
  type BlockRotation,
  type Vec3Like,
} from './block-grid';
export {
  COLLISION_PIECE_LIMITS,
  blockTopOptions,
  chunkOfCell,
  collisionMeshChunk,
  meshBlockChunk,
  shapeSource,
  type BlockLookResolver,
  type BlockMeshSource,
  type BlockTopOptions,
  type ChunkMeshPart,
  type CollisionMeshPiece,
} from './block-mesh';
export { SCULPT_LIMITS, SCULPT_OPS, columnHeights, sculptHeights, setColumnSurface, type ColumnHeights, type SculptDab, type SculptOp } from './block-sculpt';
// The paint brush (any paint target) and a block layer's surface paint.
export { BRUSH_FALLOFFS, PAINT_BRUSH_LIMITS, brushFalloff, paintBrushError, paintPoint, type BrushFalloff, type PaintBrush, type PaintLayout } from './paint-brush';
export { BLOCK_PAINT_LAYOUT, PAINT_BYTES, PAINT_CHANNELS, PAINT_CHUNK_SIZE, PAINT_VERTICES, PAINT_WETNESS_CHANNEL, chunkPaintColors, chunkPaintError, chunksOfVertex, decodeChunkPaint, encodeChunkPaint, isUnpainted, paintDab, paintOffset, unpaintedChunk, type PaintSurface } from './block-paint';
export { chunkLightmapLayout, type ChunkLightmapLayout } from './block-lightmap';
// The instance brush (paint and erase copies of an instance set on a surface).
export {
  INSTANCE_BRUSH_DEFAULTS,
  INSTANCE_BRUSH_LIMITS,
  INSTANCE_BRUSH_REACH,
  StrokeCandidates,
  applyInstanceStroke,
  candidateDrop,
  dropOntoBlockLayers,
  instanceStrokeError,
  strokeCandidates,
  type BrushBlockLayer,
  type BrushVec3,
  type InstanceBrush,
  type InstanceSetSpace,
  type InstanceStroke,
  type InstanceStrokeMode,
  type InstanceStrokeResult,
  type StrokeCandidate,
  type StrokeSurfaceDrop,
  type StrokeSurfaceSample,
} from './instance-brush';
export {
  FLAT_CORNERS,
  blockTopAt,
  cellCorners,
  cornerGradientAt,
  cornerHeightAt,
  rotateXZ,
  subdividedGradientAt,
  subdividedHeightAt,
  surfaceBelow,
  type BlockTopSample,
  type CellCorners,
  type SurfaceGrid,
  type SurfaceHit,
} from './block-surface';
export { PNG_DECODE_MAX_PIXELS, decodeBase64, decodePngRgba, encodeBase64, inflateZlib, type DecodedPng, type PngDecodeOptions } from './png-decode';
// The project save schema (save document, slots, sections, settings document).
export {
  SAVE_LIMITS,
  SAVE_META_KEY_RE,
  saveSlotMetaProblem,
  SAVE_SECTIONS,
  SAVE_THUMBNAIL_DEFAULT,
  SETTINGS_ENGINE_BINDINGS,
  canonicalSaveSchema,
  effectiveField,
  settingsDocumentOf,
  settingsValueFits,
  validateSaveSchema,
  type SaveMigration,
  type SaveSchema,
  type SaveSection,
  type SaveThumbnail,
  type SettingsEngineBinding,
  type SettingsField,
  type SettingsFieldValue,
} from './save-schema';
// Dialogue (content.dialogues / speakers / dialogueSettings), its graph kind, expressions and the runtime form.
export {
  DIALOGUE_DEFAULTS,
  DIALOGUE_DOCUMENT_ID,
  DIALOGUE_GRAPH_KIND,
  DIALOGUE_LIMITS,
  applyDialogueEffect,
  canonicalDialogue,
  canonicalDialogueSettings,
  canonicalDialogues,
  canonicalSpeaker,
  canonicalSpeakers,
  compileDialogue,
  dialogueAssetRefs,
  dialogueForRuntime,
  dialogueLineText,
  dialogueNodeProblems,
  dialogueTruthy,
  dialogueUiDocument,
  dialogueValueText,
  evalDialogueExpr,
  newDialogueGraph,
  parseDialogueCondition,
  parseDialogueEffects,
  runtimeDialogueDataProblem,
  validateDialogue,
  validateDialogueReferences,
  validateDialogues,
  validateDialogueSettings,
  validateSpeaker,
  validateSpeakers,
  withDialogueUiDocument,
  type DialogueDocument,
  type DialogueEffect,
  type DialogueEnv,
  type DialogueExpr,
  type DialogueLineText,
  type DialogueSettings,
  type DialogueSpeaker,
  type DialogueValue,
  type RuntimeDialogue,
  type RuntimeDialogueData,
  type RuntimeDialogueNode,
  type RuntimeDialogueOption,
} from './dialogue';
export { codePointLength, parseRichText, richTextVisibleLength, uiValueText, type RichStyle, type RichToken } from './rich-text';
export { UI_DIALOGUE_INPUTS, type UiDialogueInput } from './ui-documents';
// Timelines (sequencer assets).
export {
  TIMELINE_LIMITS,
  TIMELINE_TRACK_TYPES,
  TIMELINE_EASINGS,
  TIMELINE_TARGET_TRACKS,
  validateTimeline,
  validateTimelines,
  validateTimelineReferences,
  timelineRefs,
  canonicalTimeline,
  canonicalTimelines,
} from './timelines';
export type { TimelineAsset, TimelineTrack, TimelineKey, TimelineSlot, TimelineMarker, TimelineTrackType, TimelineEasing, TimelineValue } from './timelines';
export { SIGNAL_DEBUG_COMMAND_NAME, type SignalDebugCommandName } from './debug-command-names';
// The scene rules checked before Play and the export (not per command).
export { playChecks, type PlayCheck } from './play-checks';
