#!/usr/bin/env node
/**
 * Beacon Reach — self-generated sample asset generator (packet 61).
 *
 * Emits the sample's ORIGINAL content (no downloaded assets, no external
 * URLs): five short PCM WAV cues and two self-contained glTF 2.0 GLB models,
 * each with a deterministic byte layout so the provenance digests are
 * reproducible by re-running this script. The generator is a content recipe,
 * not an engine feature — it is committed under `samples/beacon-reach/` so the
 * sample's asset provenance is auditable and re-derivable.
 *
 * Output (all under samples/beacon-reach/assets/):
 *   audio/cue-{start,jump,checkpoint,death,goal}.wav — PCM mono 48 kHz 16-bit,
 *     44-byte header, ≤ 2000 ms (presentation.md §41.4 limits).
 *   model/courier.glb — a small rigid courier (Body + Arm parts, no skin/
 *     bones/external refs) with three named clips (Idle, Run, Airborne).
 *   model/beacon.glb — a small rigid beacon/pillar (two stacked boxes).
 *   provenance.json — per-asset sourceDigest (SHA-256) + byteLength + the
 *     explicit reuse license.
 *   LICENSE — the explicit reuse license for the generated content.
 *
 * Run: `node samples/beacon-reach/tools/generate-assets.mjs`. Idempotent —
 * overwrites the committed assets and re-derives provenance.json.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SAMPLE_ROOT = dirname(HERE);
const ASSETS = join(SAMPLE_ROOT, 'assets');

const LICENSE_TEXT = `Beacon Reach — generated sample content
Thirdlight M3 sample (packet 61).

All assets in this directory are ORIGINAL content generated by
samples/beacon-reach/tools/generate-assets.mjs (deterministic, no downloaded
third-party content, no external image/audio references, no fonts).

License: this generated content is provided for the Thirdlight project under
the same license as the repository. It may be copied, modified, and
redistributed with the Thirdlight project without further attribution beyond
this notice. No rights are asserted to any external (downloaded) content,
because none is used.
`;

const LICENSE_ID = 'thirdlight-sample-generated-content';

/* ------------------------------------------------------------------ WAV --- */

/** Build one PCM mono 48 kHz 16-bit WAV (44-byte header) for a sine tone. */
function buildWav(freqHz, durationMs, peakAmp = 0.4) {
  const rate = 48000;
  const frames = Math.floor((durationMs / 1000) * rate);
  const dataBytes = new ArrayBuffer(frames * 2);
  const dv = new DataView(dataBytes);
  for (let i = 0; i < frames; i += 1) {
    // A short tone with a linear fade-out envelope (no click).
    const t = i / rate;
    const env = i < frames * 0.7 ? 1 : (frames - i) / (frames * 0.3);
    const sample = Math.sin(2 * Math.PI * freqHz * t) * peakAmp * env;
    dv.setInt16(i * 2, Math.max(-32767, Math.min(32767, Math.round(sample * 32767))), true);
  }
  const dataSize = frames * 2;
  const out = new Uint8Array(44 + dataSize);
  const v = new DataView(out.buffer);
  const writeStr = (off, s) => { for (let i = 0; i < s.length; i += 1) out[off + i] = s.charCodeAt(i); };
  writeStr(0, 'RIFF'); v.setUint32(4, 36 + dataSize, true); writeStr(8, 'WAVE');
  writeStr(12, 'fmt '); v.setUint32(16, 16, true);
  v.setUint16(20, 1, true); // PCM
  v.setUint16(22, 1, true); // mono
  v.setUint32(24, rate, true);
  v.setUint32(28, rate * 2, true); // byteRate
  v.setUint16(32, 2, true); // blockAlign
  v.setUint16(34, 16, true); // bitsPerSample
  writeStr(36, 'data'); v.setUint32(40, dataSize, true);
  out.set(new Uint8Array(dataBytes), 44);
  return out;
}

/* ------------------------------------------------------------------ GLB --- */

class BinWriter {
  constructor() { this.bytes = []; }
  push(data) {
    const offset = Math.ceil(this.bytes.length / 4) * 4;
    while (this.bytes.length < offset) this.bytes.push(0);
    for (const b of data) this.bytes.push(b & 0xff);
    return { offset, length: data.length };
  }
  byteLength() { return this.bytes.length; }
  padded() {
    const out = new Uint8Array(Math.ceil(this.bytes.length / 4) * 4);
    out.set(this.bytes, 0);
    return out;
  }
}

function f32(values) {
  const b = new ArrayBuffer(values.length * 4);
  const v = new DataView(b);
  values.forEach((x, i) => v.setFloat32(i * 4, x, true));
  return [...new Uint8Array(b)];
}
function u16(values) {
  const b = new ArrayBuffer(values.length * 2);
  const v = new DataView(b);
  values.forEach((x, i) => v.setUint16(i * 2, x, true));
  return [...new Uint8Array(b)];
}

/** A unit box (8 vertices, 12 triangles) as POSITION + indices byte arrays. */
function boxBytes(halfX, halfY, halfZ) {
  const x = halfX, y = halfY, z = halfZ;
  const positions = f32([
    -x, -y, -z, x, -y, -z, x, y, -z, -x, y, -z,
    -x, -y, z, x, -y, z, x, y, z, -x, y, z,
  ]);
  const indices = u16([
    0, 1, 2, 0, 2, 3, 4, 6, 5, 4, 7, 6,
    0, 4, 5, 0, 5, 1, 1, 5, 6, 1, 6, 2,
    3, 2, 6, 3, 6, 7, 0, 3, 7, 0, 7, 4,
  ]);
  return { positions, indices };
}

/** Pack a glTF 2.0 GLB (JSON chunk + BIN chunk). */
function packGlb(jsonText, bin) {
  const jsonBytes = new TextEncoder().encode(jsonText);
  const jsonPadded = new Uint8Array(Math.ceil(jsonBytes.length / 4) * 4);
  jsonPadded.set(jsonBytes, 0);
  jsonPadded.fill(0x20, jsonBytes.length);
  const total = 12 + 8 + jsonPadded.length + 8 + bin.length;
  const out = new Uint8Array(total);
  const v = new DataView(out.buffer);
  v.setUint32(0, 0x46546c67, true);
  v.setUint32(4, 2, true);
  v.setUint32(8, total, true);
  v.setUint32(12, jsonPadded.length, true);
  v.setUint32(16, 0x4e4f534a, true);
  out.set(jsonPadded, 20);
  const binHeader = 20 + jsonPadded.length;
  v.setUint32(binHeader, bin.length, true);
  v.setUint32(binHeader + 4, 0x004e4942, true);
  out.set(bin, binHeader + 8);
  return out;
}

/**
 * Build a rigid multi-part model with named rotation/translation clips.
 * `parts`: [{ name, half, translation, clipNode: true|false }] — each part is
 * a box mesh on its own node (rigid internal parts; no skin/bones). `clips`:
 * [{ name, duration, perPart: { [partName]: { rot, trans } } }] — each clip
 * animates a rotation (and optionally translation) channel per part.
 */
function buildRigidModel({ generator, sceneName, parts, clips, colors, rootTranslation }) {
  const bin = new BinWriter();
  const bufferViews = [];
  const accessors = [];
  const meshes = [];
  const nodes = [];
  const animations = [];
  const materials = [];

  // One mesh + material per part (rigid; each part is a node with a mesh).
  parts.forEach((p, i) => {
    const box = boxBytes(p.half[0], p.half[1], p.half[2]);
    const pos = bin.push(box.positions);
    const idx = bin.push(box.indices);
    bufferViews.push({ buffer: 0, byteOffset: pos.offset, byteLength: pos.length, target: 34962 });
    bufferViews.push({ buffer: 0, byteOffset: idx.offset, byteLength: idx.length, target: 34963 });
    const [hx, hy, hz] = p.half;
    accessors.push({
      bufferView: 2 * i, componentType: 5126, count: 8, type: 'VEC3',
      min: [-hx, -hy, -hz], max: [hx, hy, hz],
    });
    accessors.push({ bufferView: 2 * i + 1, componentType: 5123, count: 36, type: 'SCALAR' });
    meshes.push({ name: `${p.name}Mesh`, primitives: [{ attributes: { POSITION: 2 * i }, indices: 2 * i + 1, material: i, mode: 4 }] });
    const c = colors[i] ?? [0.6, 0.6, 0.6, 1];
    materials.push({ name: `${p.name}Mat`, pbrMetallicRoughness: { baseColorFactor: c, metallicFactor: 0.1, roughnessFactor: 0.8 } });
    nodes.push({ name: p.name, mesh: i, translation: p.translation ?? [0, 0, 0] });
  });

  // A root node holding all parts (rigid hierarchy, unit scale, no physics).
  nodes.unshift({ name: 'Root', children: parts.map((_, i) => i + 1), ...(rootTranslation ? { translation: rootTranslation } : {}) });
  // Re-index: parts are now nodes 1..n.

  clips.forEach((clip, ci) => {
    const samplers = [];
    const channels = [];
    Object.entries(clip.perPart).forEach(([partName, spec]) => {
      const partIndex = parts.findIndex((p) => p.name === partName);
      if (partIndex < 0) return;
      const nodeIndex = partIndex + 1; // parts are nodes 1..n
      // A two-frame linear clip (identity -> target) for each present channel.
      // Sampler input/output reference the accessors actually pushed.
      const duration = clip.duration ?? 1;
      const times = bin.push(f32([0, duration]));
      bufferViews.push({ buffer: 0, byteOffset: times.offset, byteLength: times.length });
      const timesAccessor = accessors.length;
      accessors.push({ bufferView: bufferViews.length - 1, componentType: 5126, count: 2, type: 'SCALAR', min: [0], max: [duration] });
      if (spec.rot) {
        const [x, y, z, w] = spec.rot;
        const n = Math.hypot(x, y, z, w);
        const r = bin.push(f32([0, 0, 0, 1, x / n, y / n, z / n, w / n]));
        bufferViews.push({ buffer: 0, byteOffset: r.offset, byteLength: r.length });
        const outAccessor = accessors.length;
        accessors.push({ bufferView: bufferViews.length - 1, componentType: 5126, count: 2, type: 'VEC4' });
        samplers.push({ input: timesAccessor, output: outAccessor, interpolation: 'LINEAR' });
        channels.push({ sampler: samplers.length - 1, target: { node: nodeIndex, path: 'rotation' } });
      }
      if (spec.trans) {
        const tr = bin.push(f32([0, 0, 0, spec.trans[0], spec.trans[1], spec.trans[2]]));
        bufferViews.push({ buffer: 0, byteOffset: tr.offset, byteLength: tr.length });
        const outAccessor = accessors.length;
        accessors.push({ bufferView: bufferViews.length - 1, componentType: 5126, count: 2, type: 'VEC3' });
        samplers.push({ input: timesAccessor, output: outAccessor, interpolation: 'LINEAR' });
        channels.push({ sampler: samplers.length - 1, target: { node: nodeIndex, path: 'translation' } });
      }
    });
    animations.push({ name: clip.name, samplers, channels });
  });

  const json = {
    asset: { version: '2.0', generator },
    scene: 0,
    scenes: [{ name: sceneName, nodes: [0] }],
    nodes,
    meshes,
    materials,
    accessors,
    bufferViews,
    buffers: [{ byteLength: bin.byteLength() }],
    animations,
  };
  return packGlb(JSON.stringify(json), bin.padded());
}

/* ----------------------------------------------------------------- main --- */

const sha256Hex = (bytes) => createHash('sha256').update(bytes).digest('hex');

const CUES = [
  { name: 'start', freqHz: 660, durationMs: 180 },
  { name: 'jump', freqHz: 520, durationMs: 140 },
  { name: 'checkpoint', freqHz: 880, durationMs: 220 },
  { name: 'death', freqHz: 180, durationMs: 320 },
  { name: 'goal', freqHz: 990, durationMs: 420 },
];

// The courier (the player's model): legs, body, head and a swinging arm,
// sized to the 1.8 m player capsule. The model origin is the capsule center
// (the player entity's position), so the root sits 0.9 m lower: feet on the
// ground. Three clips: Idle, Run, Airborne.
const COURIER = buildRigidModel({
  generator: 'thirdlight-beacon-reach-generator',
  sceneName: 'Courier',
  rootTranslation: [0, -0.9, 0],
  parts: [
    { name: 'Legs', half: [0.2, 0.3, 0.16], translation: [0, 0.3, 0] },
    { name: 'Body', half: [0.28, 0.42, 0.2], translation: [0, 1.02, 0] },
    { name: 'Head', half: [0.18, 0.18, 0.18], translation: [0, 1.62, 0] },
    { name: 'Arm', half: [0.08, 0.34, 0.08], translation: [0.36, 1.05, 0] },
  ],
  colors: [[0.25, 0.3, 0.45, 1], [0.85, 0.45, 0.2, 1], [0.95, 0.8, 0.65, 1], [0.3, 0.55, 0.85, 1]],
  clips: [
    { name: 'Idle', duration: 1.0, perPart: { Arm: { rot: [0, 0, 0.1, 0.995] } } },
    { name: 'Run', duration: 0.4, perPart: { Arm: { rot: [0.5, 0, 0, 0.866] }, Legs: { rot: [-0.2, 0, 0, 0.98] } } },
    { name: 'Airborne', duration: 0.6, perPart: { Arm: { rot: [0, 0, 0.7, 0.714] }, Legs: { trans: [0, 0.1, 0] } } },
  ],
});

// The beacon: a rigid pillar (two stacked boxes) — a decoration, no clips.
const BEACON = buildRigidModel({
  generator: 'thirdlight-beacon-reach-generator',
  sceneName: 'Beacon',
  parts: [
    { name: 'Pillar', half: [0.3, 0.8, 0.3], translation: [0, 0.8, 0] },
    { name: 'Lamp', half: [0.45, 0.25, 0.45], translation: [0, 1.75, 0] },
  ],
  colors: [[0.2, 0.25, 0.3, 1], [0.95, 0.85, 0.4, 1]],
  clips: [],
});

function main() {
  const audioDir = join(ASSETS, 'audio');
  const modelDir = join(ASSETS, 'model');
  mkdirSync(audioDir, { recursive: true });
  mkdirSync(modelDir, { recursive: true });
  writeFileSync(join(SAMPLE_ROOT, 'LICENSE'), LICENSE_TEXT);

  const provenance = {
    sample: 'beacon-reach',
    generatedBy: 'samples/beacon-reach/tools/generate-assets.mjs',
    license: LICENSE_ID,
    licenseText: join(SAMPLE_ROOT, 'LICENSE'),
    assets: [],
  };

  for (const cue of CUES) {
    const bytes = buildWav(cue.freqHz, cue.durationMs);
    const path = `audio/cue-${cue.name}.wav`;
    writeFileSync(join(ASSETS, path), bytes);
    provenance.assets.push({
      id: `audio-${cue.name}`,
      kind: 'audio',
      path,
      sourceDigest: sha256Hex(bytes),
      sourceByteLength: bytes.byteLength,
      profile: 'pcm-wav',
      recipe: { sampleRate: 48000, channels: 1, bitsPerSample: 16, freqHz: cue.freqHz, durationMs: cue.durationMs },
    });
  }

  for (const [name, bytes] of [['courier', COURIER], ['beacon', BEACON]]) {
    const path = `model/${name}.glb`;
    writeFileSync(join(ASSETS, path), bytes);
    provenance.assets.push({
      id: `model-${name}`,
      kind: 'model',
      path,
      sourceDigest: sha256Hex(bytes),
      sourceByteLength: bytes.byteLength,
      profile: 'glb-gltf2',
      clips: name === 'courier' ? ['Idle', 'Run', 'Airborne'] : [],
    });
  }

  writeFileSync(join(ASSETS, 'provenance.json'), JSON.stringify(provenance, null, 2) + '\n');
  console.log(`generated ${provenance.assets.length} assets under ${ASSETS}`);
  for (const a of provenance.assets) console.log(`  ${a.id}: ${a.path} ${a.sourceByteLength}B ${a.sourceDigest.slice(0, 12)}…`);
}

main();