/**
 * @thirdlight/protocol — public surface: HTTP payload types, WS event types
 * and bridge message types with strict validators, ID syntax constants and
 * allowlist constants.
 *
 * Thirdlight wire protocol (docs/contracts/sessions.md):
 * the strict JSON payload discipline (project-model byte rules +
 * unknown-field rejection), the session-layer error model, the
 * exhaustive WS event catalog with builders and
 * validators, and the exhaustive bridge message allowlist with
 * strict validators. Pure: no I/O, no Node built-ins, no DOM
 * (project-model values + commands types only).
 */

// ID syntax constants + validators.
export {
  CONN_ID_RE,
  CONTENT_ID_RE,
  NONCE_RE,
  PLAY_SESSION_ID_RE,
  PROJECT_ID_RE,
  RELAY_ID_RE,
  REQUEST_ID_RE,
  SESSION_ID_RE,
  SESSION_KINDS,
  WSTOKEN_RE,
  isConnId,
  isContentId,
  isNonce,
  isPlaySessionId,
  isProjectId,
  isRelayId,
  isRequestId,
  isSessionId,
  isWsToken,
  type SessionKind,
} from './ids';

// Session-layer error model.
export {
  ERROR_CODES,
  MESSAGE_LIMIT,
  WS_CLOSE_FRAME_TOO_BIG,
  WS_CLOSE_NORMAL,
  WS_CLOSE_PROTOCOL,
  WS_CLOSE_UNAUTHORIZED,
  clipMessage,
  sessionError,
  statusFor,
  type ErrorClass,
  type SessionError,
  type SessionErrorCode,
} from './errors';

// Strict JSON payload discipline.
export {
  checkField,
  checkOptionalObject,
  checkShape,
  isPlainObject,
  isStringNoControl,
  parseStrictJson,
  parseStrictJsonBytes,
  type FieldErrorResult,
  type FieldVerdict,
  type StrictParseResult,
} from './strict';

// HTTP payload types + strict validators.
export {
  ALL_COMMAND_OPS,
  QUERY_OPS,
  SCREENSHOT_DATA_URL_MAX,
  SCREENSHOT_MAX_WIDTH_DEFAULT,
  SCREENSHOT_MAX_WIDTH_MAX,
  SCREENSHOT_MAX_WIDTH_MIN,
  isMutationOp,
  parseAdminCreateProjectRequest,
  parseAdminNoArgsBody,
  parseCommandEnvelope,
  parseEstablishRequest,
  parsePlayStartRequest,
  parseScreenshotRequest,
  type AdminCreateProjectRequest,
  type EstablishRequest,
  type PlayStartRequest,
  type ScreenshotRequest,
  // test/debug start options.
  type PlayStartOptions,
  PLAY_START_PROJECT_SAVE_MAX_BYTES,
  PROJECT_SAVE_FORMAT,
  PLAY_START_VARIABLES_MAX,
  PLAY_START_VARIABLE_MAX_CHARS,
} from './http';

// Content transport wire shapes + strict validators.
export {
  CONTENT_ASSETS_LIMIT_DEFAULT,
  CONTENT_ASSETS_LIMIT_MAX,
  CONTENT_ASSET_BYTES_CACHE,
  CONTENT_ASSET_BYTES_MAX,
  CONTENT_INSPECT_TIMEOUT_MS,
  CONTENT_JOB_KINDS,
  CONTENT_JOB_RESULT_TTL_MS,
  CONTENT_JOB_STATES,
  CONTENT_OPEN_STAGES,
  CONTENT_PROPOSAL_MAX_BYTES,
  CONTENT_PUBLISH_CONCURRENCY_GLOBAL,
  CONTENT_PUBLISH_CONCURRENCY_PER_PROJECT,
  CONTENT_PUBLISH_TIMEOUT_MS,
  CONTENT_STAGED_BYTES_PER_PROJECT,
  CONTENT_STAGE_CREATE_RESPONSE_MAX,
  INSTANCE_BUFFER_INLINE_MAX,
  CONTENT_STAGE_MAX,
  CONTENT_UPLOAD_FRAME_MAX,
  checkUploadFrame,
  containsBinaryValue,
  encodeBinaryFreeStateFrame,
  parseAssetByteParams,
  parseContentAssetsQuery,
  parseJobId,
  parseStageCreateRequest,
  parseStageId,
  parseUploadFrameHeaders,
  validateContentJobView,
  type AssetByteParams,
  type ContentAssetsQuery,
  type ContentJobKind,
  type ContentJobState,
  type ContentJobView,
  type UploadFrameCheckInput,
  type UploadFrameVerdict,
} from './content';

// WS event catalog (exhaustive).
export {
  CLIENT_EVENT_TYPES,
  PLAY_STOP_REASONS,
  PLAY_STOP_REQUEST_REASONS,
  SERVER_EVENT_TYPES,
  WS_IN_FRAME_MAX,
  WS_OUT_FRAME_MAX,
  WS_SCREENSHOT_ACK_MAX,
  enforceDefaultFrameBound,
  inboundFrameAllowed,
  makeAttached,
  makeDiagnosticsRequest,
  makeErrorEvent,
  makeGameControlRequest,
  makeGameObserveRequest,
  makeInputRelayRequest,
  makeMutationApplied,
  makePong,
  makePlayStarted,
  playSnapshotPath,
  makePlayStopRequest,
  makePlayStopped,
  makeScreenshotRequest,
  parseInboundEvent,
  type InboundEvent,
  type PlayStopReason,
  type PlayStopRequestReason,
  type PlaySnapshotRef,
  type RuntimeSnapshotDoc,
  type PlayStartResolved,
  type ServerEventType,
  type ClientEventType,
} from './ws-events';

// Bridge message allowlist + strict validators.
export {
  BRIDGE_EDITOR_TO_PREVIEW_TYPES,
  BRIDGE_INPUT_MAX_BYTES,
  BRIDGE_DEBUG_MAX_BREAKPOINTS,
  BRIDGE_DEBUG_RESULT_MAX_BYTES,
  BRIDGE_DEBUG_COMMANDS,
  BRIDGE_INPUT_MAX_FRAMES,
  BRIDGE_LOAD_PROGRESS_MAX_BYTES,
  BRIDGE_MESSAGE_MAX_BYTES,
  BRIDGE_PREVIEW_TO_EDITOR_TYPES,
  BRIDGE_VERSION,
  LOAD_PHASES,
  validateBridgeEditorToPreview,
  validateBridgePreviewToEditor,
  type BridgeEditorToPreviewType,
  type BridgePreviewToEditorType,
  type LoadPhase,
} from './bridge';

// Play delivery: locator/manifest identity + bounded input relay.
export {
  BUILD_OPTIONS_RECORD,
  INPUT_RELAY_ACK_TIMEOUT_MS,
  INPUT_RELAY_MAX_BODY_BYTES,
  INPUT_RELAY_MAX_FRAMES,
  INPUT_RELAY_MAX_STEPS,
  INPUT_RELAY_MODE,
  INPUT_RELAY_RESULT_MAX_BYTES,
  MANIFEST_KEYS,
  PLAY_CONTENT_ARTIFACT_MAX_BYTES,
  PLAY_CONTENT_GRACE_SECONDS,
  PLAY_CONTENT_ID_BYTES,
  PLAY_CONTENT_MANIFEST_MAX_BYTES,
  PLAY_CONTENT_TTL_SECONDS,
  RUNTIME_CONTENT_MANIFEST_VERSION,
  RUNTIME_CONTENT_TYPE,
  buildOptionsRecordBytes,
  classifyLocatorPath,
  manifestBuildIdInput,
  orderManifest,
  parseInputRelayRequest,
  parseRelayPointer,
  parseRelayGamepad,
  parseRelayUiEdges,
  relayFrameEnd,
  RELAY_UI_EDGES,
  RELAY_MAX_UI_EDGES,
  RELAY_GAMEPAD_BUTTONS,
  RELAY_GAMEPAD_AXES,
  type RelayGamepad,
  type RelayUiEdge,
  type RelayPointer,
  redactContentId,
  validateInputRelayResult,
  type InputRelayRequest,
  type InputRelayResultDoc,
  type LocatorPath,
  type RelayFrame,
  type RelayJumpPhase,
} from './delivery';

// v3 authoring wire + the game control/observation relay.
export {
  CHANGE_TYPES,
  GAME_CONTROL_BODY_MAX_BYTES,
  GAME_CONTROL_COMMANDS,
  SIGNAL_DEBUG_COMMAND_NAME,
  debugCommandCallProblem,
  GAME_CONTROL_RESULT_MAX_BYTES,
  PLAY_STATES,
  GAME_GESTURES,
  GAME_INPUT_MODES,
  GAME_OBSERVATION_MAX_BYTES,
  GAME_OBSERVE_BODY_MAX_BYTES,
  GAME_OBSERVE_TIMEOUT_DEFAULT_MS,
  relayAnswerWithinMs,
  RELAY_ANSWER_WITHIN_MAX_MS,
  REPLAY_RESTART_STATES,
  GAME_OBSERVE_TIMEOUT_MAX_MS,
  GAME_OBSERVE_TIMEOUT_MIN_MS,
  GAME_RELAY_ERROR_CODES,
  GAME_SOUND_STATUSES,
  RUN_ID_RE,
  V3_CONTENT_KEYS,
  V3_ENVELOPE_KEYS,
  V3_MUTATION_OPS,
  V3_QUERY_OPS,
  V3_SCHEMA_VERSION,
  V3_SCENE_KEYS,
  V3_STORAGE_VERSION,
  CONTENT_PROJECTION_KEYS,
  ANIMATION_ROLE_KEYS,
  parseStageInspectRequest,
  parseProjectFilesQuery,
  parseProjectFileInspectRequest,
  parseTexturePackRequest,
  TEXTURE_PACK_LAYERS_MAX,
  type TexturePackChannel,
  type TexturePackRequest,
  type ProjectFileInspectRequest,
  type AnimationRoleBindingValue,
  type AnimationRolesValue,
  type StageInspectRequest,
  gameRelayError,
  isGameRelayId,
  isRunId,
  isSafeIdentifier,
  parseGameControlRequest,
  parseGameObserveRequest,
  validateChangeFrame,
  validateFullStateFrame,
  validateGameControlResult,
  validateGameObservation,
  validateQueryResultV3,
  validateV3ContentBlock,
  validateV3EnvelopeShape,
  validateV3MutationArgs,
  validateV3SceneShape,
  type GameControlCommand,
  type GameControlRequest,
  type GameObserveRequest,
  type PlayState,
} from './m3';// Light baking shared by the editor and the backend.
export {
  bakeHashes,
  bakeLightMode,
  hash16,
  isBakeStatic,
  LIGHTMAP_MAX_ATLAS,
  LIGHTMAP_MAX_ATLASES,
  packLightmaps,
  type BakeHashEntity,
  type LightmapItem,
  type LightmapPacking,
  type LightmapPlacement,
} from './bake';

// The change record on the WS (no previous side; keyed lists as deltas).
export { WIRE_LIST_KEYS, fromWireChange, toWireChange, type WireListDelta } from './wire-change';

// Importing an asset tool's job export (a folder or zip: a GLB and manifest.json).
export {
  JOB_EXPORT_LIMITS,
  JOB_EXPORT_MANIFEST,
  isJobExportPath,
  parseJobExportManifest,
  parseJobExportRequest,
  type JobExportFile,
  type JobExportManifest,
  type JobExportRequest,
} from './job-export';

// The ops that create a resource or a scene (each takes an optional `folder`); the editor adds its current folder to them.
export { RESOURCE_CREATING_OPS } from '@thirdlight/project-model/limits';
