/**
 * The export bundle build.
 *
 * The bundle is built with the SAME pinned esbuild 0.28.2 option set as the
 * play-preview bundle; only the entry file and the allowed graph differ. Two
 * in-memory virtual modules feed the per-snapshot facts:
 *
 *   `thirdlight:export-artifacts`  — the manifest-declared asset paths and one
 *     relative `fetch("./<declared path>")` call site per path (never a URL,
 *     never an undeclared path). This is the export fetch rule.
 *   `thirdlight:export-modules`  — the simulation module specs the manifest
 *     names.
 *
 * Nothing here executes project source.
 */
import { build } from 'esbuild';
import { ENGINE_MODULES } from '@thirdlight/project-model';

import type { ContentClosureM3 } from './content-closure';

/** The pinned esbuild 0.28.2 option set (normative). */
export const PINNED_OPTIONS = {
  bundle: true,
  platform: 'browser',
  format: 'iife',
  treeShaking: false,
  sourcemap: false,
  minify: false,
  // three's DRACOLoader computes default decoder URLs from import.meta.url at
  // module load, which an IIFE does not have; the page URL stands in (the
  // loader port always sets ./decoders/).
  define: { 'import.meta.url': 'location.href' },
} as const;

/**
 * Every `import … from 'three'` (the engine's and three's own
 * addons': GLTFLoader, KTX2Loader, SkeletonUtils, …) resolves to
 * `three/webgpu`, so a bundle links one three build — the WebGPURenderer
 * build (`three.core.js` + `three.webgpu.js`) — and not `three.module.js`
 * (the WebGLRenderer, its shader chunks and the WebGL PMREM, which nothing
 * uses). `three/webgpu` re-exports the whole core, so
 * every class is the same object; the seven names only `three` has
 * (WebGLRenderer, WebGLCubeRenderTarget, WebGLUtils, ShaderChunk, ShaderLib,
 * UniformsLib, UniformsUtils) are used by no bundled module.
 */
export const THREE_WEBGPU_ONLY_PLUGIN = {
  name: 'thirdlight-three-webgpu-only',
  setup(b: {
    onResolve: (o: { filter: RegExp }, cb: (a: { kind: string; resolveDir: string }) => Promise<unknown>) => void;
    resolve: (path: string, o: { kind: string; resolveDir: string }) => Promise<unknown>;
  }): void {
    b.onResolve({ filter: /^three$/ }, (a) => b.resolve('three/webgpu', { kind: a.kind, resolveDir: a.resolveDir }));
  },
};

/** The virtual module specifiers (allowed graph nodes; see graph.ts). */
export const ARTIFACTS_MODULE = 'thirdlight:export-artifacts';
/** The generated artifacts module: declared asset paths + one relative fetch each. */
export function artifactsModuleSource(assetPaths: readonly string[]): string {
  const rows = assetPaths.map((p) => `  case ${JSON.stringify(p)}: return fetch(${JSON.stringify(`./${p}`)}, { credentials: "omit", signal });`);
  return [
    '// generated by @thirdlight/exporter (packet 36) — manifest-declared relative artifact reads',
    `export const assetPaths = ${JSON.stringify(assetPaths)};`,
    'export function readAsset(path, signal) {',
    '  switch (path) {',
    ...rows,
    '    default: return null;',
    '  }',
    '}',
    '',
  ].join('\n');
}

/**
 * The generated module-spec module (`thirdlight:export-modules`).
 * It imports the `SimulationModuleSpec` of exactly the simulation modules the
 * manifest names (those a package outside the runtime provides), in the
 * engine table's dependency order — a game without them links none of that
 * package's code.
 */
export const MODULES_MODULE = 'thirdlight:export-modules';
export function modulesModuleSource(moduleIds: readonly string[]): string {
  const rows = ENGINE_MODULES.filter((m) => m.spec !== undefined && moduleIds.includes(m.id));
  return [
    '// generated by @thirdlight/exporter (phase 24.3) — the simulation module specs this manifest names',
    ...rows.map((m, i) => `import { ${m.spec as string} as spec${i} } from ${JSON.stringify(m.package)};`),
    `export const moduleSpecs = [${rows.map((_, i) => `spec${i}`).join(', ')}];`,
    '',
  ].join('\n');
}

/** The esbuild plugin serving `thirdlight:export-modules` (imports resolve from the entry's directory). */
function modulesPlugin(entry: string, moduleIds: readonly string[]): unknown {
  return {
    name: 'thirdlight-export-modules',
    setup(b: {
      onResolve: (o: { filter: RegExp }, cb: (a: { path: string }) => { path: string; namespace: string }) => void;
      onLoad: (o: { filter: RegExp; namespace: string }, cb: (a: { path: string }) => { contents: string; loader: 'js'; resolveDir: string }) => void;
    }): void {
      b.onResolve({ filter: /^thirdlight:export-modules$/ }, () => ({ path: 'export-modules', namespace: 'thirdlight-export-modules' }));
      b.onLoad({ filter: /.*/, namespace: 'thirdlight-export-modules' }, () => ({ contents: modulesModuleSource(moduleIds), loader: 'js', resolveDir: entry.replace(/[\\/][^\\/]*$/, '') }));
    },
  };
}

export interface M2BundleResult {
  ok: true;
  bytes: Uint8Array;
  metafile: { inputs: Record<string, unknown> };
}

export interface M2BundleFailure {
  ok: false;
  modules: string[];
  message: string;
}

/**
 * The simulation worker bundle (`js/sim-worker.js`): the same
 * pinned option set, entry `export-sim-worker.ts` (the game host's worker
 * core + physics-rapier with its inlined WASM). The worker reads nothing
 * itself (the page sends it the scenes and script URLs); given
 * the manifest's module ids it links `thirdlight:export-modules` (the
 * simulation module specs those ids name) — the 3D physics entry needs none.
 */
export async function buildSimWorkerBundle(entry: string, moduleIds?: readonly string[]): Promise<M2BundleResult | M2BundleFailure> {
  try {
    const r = await build({
      ...PINNED_OPTIONS,
      entryPoints: [entry],
      write: false,
      metafile: true,
      plugins: [...(moduleIds !== undefined ? [modulesPlugin(entry, moduleIds) as never] : []), THREE_WEBGPU_ONLY_PLUGIN as never],
    });
    const out = r.outputFiles?.[0]?.contents;
    const metafile = r.metafile as { inputs: Record<string, unknown> } | undefined;
    if (out === undefined || out.length === 0 || metafile === undefined) return { ok: false, modules: ['(no bundle output)'], message: 'the simulation worker bundle build produced no output' };
    return { ok: true, bytes: out, metafile };
  } catch (e) {
    return { ok: false, modules: [e instanceof Error ? e.message.slice(0, 200) : String(e)], message: e instanceof Error ? e.message : String(e) };
  }
}

/**
 * The export bundle build: the entry is the bootstrap
 * (`export-bootstrap-m3.ts`) plus the two virtual modules above. The
 * composition is owned by `game-host`; compiled behaviors are separate
 * artifacts the game host links at run time, not part of this bundle.
 */
export async function buildM3Bundle(input: {
  bootstrapEntry: string;
  closure: ContentClosureM3;
}): Promise<M2BundleResult | M2BundleFailure> {
  // The scene files and instance buffers are read the same way.
  const assetPaths = [
    ...input.closure.assetArtifacts.map((a) => a.path),
    ...input.closure.sceneArtifacts.map((a) => a.path),
    ...input.closure.bufferArtifacts.map((a) => a.path),
    // The manifest's content files.
    ...input.closure.contentFileArtifacts.map((a) => a.path),
  ];
  const plugin = {
    name: 'thirdlight-export-closure-m3',
    setup(b: {
      onResolve: (o: { filter: RegExp }, cb: (a: { path: string }) => { path: string; namespace: string }) => void;
      onLoad: (o: { filter: RegExp; namespace: string }, cb: (a: { path: string }) => { contents: string; loader: 'js' }) => void;
    }): void {
      b.onResolve({ filter: /^thirdlight:export-artifacts$/ }, () => ({ path: 'export-artifacts', namespace: 'thirdlight-export' }));
      b.onLoad({ filter: /.*/, namespace: 'thirdlight-export' }, (a) => ({
        contents: artifactsModuleSource(assetPaths),
        loader: 'js',
      }));
    },
  };
  try {
    const r = await build({
      ...PINNED_OPTIONS,
      entryPoints: [input.bootstrapEntry],
      write: false,
      metafile: true,
      plugins: [plugin as never, modulesPlugin(input.bootstrapEntry, input.closure.moduleIds) as never, THREE_WEBGPU_ONLY_PLUGIN as never],
    });
    const out = r.outputFiles?.[0]?.contents;
    const metafile = r.metafile as { inputs: Record<string, unknown> } | undefined;
    if (out === undefined || out.length === 0 || metafile === undefined) {
      return { ok: false, modules: ['(no bundle output)'], message: 'the M3 export bundle build produced no output' };
    }
    return { ok: true, bytes: out, metafile };
  } catch (e) {
    const names: string[] = [];
    const failure = e as { errors?: Array<{ id?: string; location?: { file?: string }; text?: string }> };
    for (const er of failure?.errors ?? []) {
      const name = er.id ?? er.location?.file ?? er.text ?? '';
      if (name !== '' && !names.includes(name)) names.push(name);
      if (names.length >= 8) break;
    }
    if (names.length === 0) names.push(e instanceof Error ? e.message : String(e));
    return { ok: false, modules: names.slice(0, 8), message: e instanceof Error ? e.message : String(e) };
  }
}
