/**
 * Packet 36 — the M2 export bundle build (export.md §5.1–§5.3, §5.2 graph).
 *
 * The bundle is built from the SAME bootstrap source with the SAME pinned
 * esbuild 0.28.2 option set as the M1 export and the play-preview bundle; only
 * the entry file and the allowed graph differ (dependencies.md §4.2). Two
 * in-memory esbuild plugins feed the per-snapshot facts:
 *
 *   `thirdlight:export-artifacts`  — the manifest-declared asset paths and one
 *     relative `fetch("./<declared path>")` call site per path (never a URL,
 *     never an undeclared path). This is the §17.5 export fetch rule.
 *   `thirdlight:export-behaviors`  — the statically linked compiled behavior
 *     outputs of this snapshot (one namespace import per `outputDigest`).
 *
 * Nothing here executes project source: the behavior bytes are the packet-33
 * compiler outputs, linked as static inputs exactly like `runtime` and
 * `three-adapter`.
 */
import { build } from 'esbuild';

import type { ContentClosureM3 } from './content-closure';

/** export.md §5.3 — the pinned esbuild 0.28.2 option set (normative). */
export const PINNED_OPTIONS = {
  bundle: true,
  platform: 'browser',
  format: 'iife',
  treeShaking: false,
  sourcemap: false,
  minify: false,
  // three's DRACOLoader computes default decoder URLs from import.meta.url at
  // module load, which an IIFE does not have; the page URL stands in (the
  // loader port always sets ./decoders/).
  define: { 'import.meta.url': 'location.href' },
} as const;

/** The virtual module specifiers (allowed graph nodes; see graph.ts). */
export const ARTIFACTS_MODULE = 'thirdlight:export-artifacts';
/** The generated artifacts module: declared asset paths + one relative fetch each. */
export function artifactsModuleSource(assetPaths: readonly string[]): string {
  const rows = assetPaths.map((p) => `  case ${JSON.stringify(p)}: return fetch(${JSON.stringify(`./${p}`)}, { credentials: "omit", signal });`);
  return [
    '// generated by @thirdlight/exporter (packet 36) — manifest-declared relative artifact reads',
    `export const assetPaths = ${JSON.stringify(assetPaths)};`,
    'export function readAsset(path, signal) {',
    '  switch (path) {',
    ...rows,
    '    default: return null;',
    '  }',
    '}',
    '',
  ].join('\n');
}

export interface M2BundleResult {
  ok: true;
  bytes: Uint8Array;
  metafile: { inputs: Record<string, unknown> };
}

export interface M2BundleFailure {
  ok: false;
  modules: string[];
  message: string;
}

/**
 * Packet 58 — the M3 export bundle build (delivery.md §3, export.md §5). The
 * same pinned esbuild 0.28.2 option set as M1/M2; the entry is the M3 bootstrap
 * (`export-bootstrap-m3.ts`) and the only generated virtual module is
 * `thirdlight:export-artifacts` (the declared asset paths + one relative fetch
 * each). The M3 composition is owned by `game-host` (no second exporter file
 * and no behavior outputs — M3 fails closed on source-bearing behaviors).
 */
export async function buildM3Bundle(input: {
  bootstrapEntry: string;
  closure: ContentClosureM3;
}): Promise<M2BundleResult | M2BundleFailure> {
  const assetPaths = input.closure.assetArtifacts.map((a) => a.path);
  const plugin = {
    name: 'thirdlight-export-closure-m3',
    setup(b: {
      onResolve: (o: { filter: RegExp }, cb: (a: { path: string }) => { path: string; namespace: string }) => void;
      onLoad: (o: { filter: RegExp; namespace: string }, cb: (a: { path: string }) => { contents: string; loader: 'js' }) => void;
    }): void {
      b.onResolve({ filter: /^thirdlight:export-artifacts$/ }, () => ({ path: 'export-artifacts', namespace: 'thirdlight-export' }));
      b.onLoad({ filter: /.*/, namespace: 'thirdlight-export' }, (a) => ({
        contents: artifactsModuleSource(assetPaths),
        loader: 'js',
      }));
    },
  };
  try {
    const r = await build({
      ...PINNED_OPTIONS,
      entryPoints: [input.bootstrapEntry],
      write: false,
      metafile: true,
      plugins: [plugin as never],
    });
    const out = r.outputFiles?.[0]?.contents;
    const metafile = r.metafile as { inputs: Record<string, unknown> } | undefined;
    if (out === undefined || out.length === 0 || metafile === undefined) {
      return { ok: false, modules: ['(no bundle output)'], message: 'the M3 export bundle build produced no output' };
    }
    return { ok: true, bytes: out, metafile };
  } catch (e) {
    const names: string[] = [];
    const failure = e as { errors?: Array<{ id?: string; location?: { file?: string }; text?: string }> };
    for (const er of failure?.errors ?? []) {
      const name = er.id ?? er.location?.file ?? er.text ?? '';
      if (name !== '' && !names.includes(name)) names.push(name);
      if (names.length >= 8) break;
    }
    if (names.length === 0) names.push(e instanceof Error ? e.message : String(e));
    return { ok: false, modules: names.slice(0, 8), message: e instanceof Error ? e.message : String(e) };
  }
}
