/**
 * Projects stored outside the data root (in a game's own repository).
 *
 * The data root keeps a registry, `<root>/registry.json`, mapping a project id
 * to the folder that holds its marker file. The marker, `thirdlight.json`,
 * sits at the game's root and names the subfolder that holds the project
 * files (`project.json`, `scenes/`, `sources/`, `.thirdlight/`), by default
 * `thirdlight/`. Projects in `<root>/projects/<id>` are not in the registry and
 * keep working unchanged.
 *
 * Absolute paths enter only here, at registration (an owner-token operation);
 * every other workspace operation still addresses a project by its id.
 */
import { closeSync, existsSync, fsyncSync, openSync, readFileSync, realpathSync, renameSync, statSync, writeSync } from 'node:fs';
import { dirname, isAbsolute, join, normalize, relative, sep } from 'node:path';

export const REGISTRY_FILE = 'registry.json';
export const MARKER_FILE = 'thirdlight.json';
export const DEFAULT_PROJECT_SUBDIR = 'thirdlight';
const ID_RE = /^[a-z0-9][a-z0-9_-]{0,63}$/;
const SUBDIR_RE = /^[a-z0-9][a-z0-9._-]{0,63}$/i;

/** The engine a project was made with (informational; see the backend's pin check). */
export interface EnginePin {
  version: string;
  commit: string;
  lockfileDigest: string;
}

/** The `thirdlight.json` marker at a game's root. */
export interface ProjectMarker {
  thirdlightProject: 1;
  projectId: string;
  name: string;
  /** The subfolder (relative to the marker) holding the project files. */
  projectDir: string;
  engine?: EnginePin;
}

/** One registered project: the marker folder and the resolved project folder. */
export interface RegisteredProject {
  folder: string;
  /** `folder/<marker.projectDir>` — the workspace's project directory. */
  projectDir: string;
  /** The realpath of `projectDir` at registration (a later symlink swap is refused). */
  realDir: string;
  /** Why the entry cannot be used right now (the folder or marker went missing), if so. */
  unavailable?: string;
}

/** Is `child` equal to or inside `parent` (both real, absolute)? */
export function isWithin(parent: string, child: string): boolean {
  if (child === parent) return true;
  const rel = relative(parent, child);
  return rel !== '' && !rel.startsWith('..') && !isAbsolute(rel) && !rel.split(sep).includes('..');
}

export function readMarker(folder: string): { ok: true; marker: ProjectMarker } | { ok: false; message: string } {
  const p = join(folder, MARKER_FILE);
  let text: string;
  try {
    text = readFileSync(p, 'utf8');
  } catch {
    return { ok: false, message: `no readable ${MARKER_FILE} in ${folder}` };
  }
  let v: unknown;
  try {
    v = JSON.parse(text);
  } catch {
    return { ok: false, message: `${MARKER_FILE} in ${folder} is not valid JSON` };
  }
  const m = v as Partial<ProjectMarker>;
  if (typeof v !== 'object' || v === null || m.thirdlightProject !== 1) {
    return { ok: false, message: `${MARKER_FILE} in ${folder} is not a Thirdlight project marker (thirdlightProject: 1)` };
  }
  if (typeof m.projectId !== 'string' || !ID_RE.test(m.projectId)) return { ok: false, message: `${MARKER_FILE}: projectId must match [a-z0-9][a-z0-9_-]{0,63}` };
  if (typeof m.name !== 'string' || m.name.length === 0 || m.name.length > 128) return { ok: false, message: `${MARKER_FILE}: name must be 1-128 characters` };
  const projectDir = m.projectDir ?? DEFAULT_PROJECT_SUBDIR;
  if (typeof projectDir !== 'string' || !SUBDIR_RE.test(projectDir) || projectDir === '.' || projectDir === '..') {
    return { ok: false, message: `${MARKER_FILE}: projectDir must be one plain subfolder name` };
  }
  return { ok: true, marker: { thirdlightProject: 1, projectId: m.projectId, name: m.name, projectDir, ...(m.engine !== undefined ? { engine: m.engine } : {}) } };
}

export function markerBytes(marker: ProjectMarker): Uint8Array {
  return new TextEncoder().encode(`${JSON.stringify(marker, null, 2)}\n`);
}

/** The `.gitignore` written into a project folder: Thirdlight's process state stays out of git. */
export const PROJECT_GITIGNORE =
  '# Thirdlight process state: ownership, recovery snapshots, staging, caches.\n' +
  '# Regenerated by the backend; never commit it.\n' +
  '.thirdlight/\n';

/** Write a small file atomically (temp + fsync + rename + dir fsync). */
export function writeSmallFileAtomic(path: string, bytes: Uint8Array): void {
  const tmp = join(dirname(path), `.${Date.now().toString(36)}-${process.pid}.tmp`);
  const fd = openSync(tmp, 'wx', 0o644);
  try {
    let off = 0;
    while (off < bytes.length) off += writeSync(fd, bytes, off, bytes.length - off);
    fsyncSync(fd);
  } finally {
    closeSync(fd);
  }
  renameSync(tmp, path);
  try {
    const d = openSync(dirname(path), 'r');
    try {
      fsyncSync(d);
    } finally {
      closeSync(d);
    }
  } catch {
    // directory fsync is best effort
  }
}

/** Resolve one registry entry (reads the marker; never throws). */
export function resolveEntry(folder: string, projectId: string): RegisteredProject {
  const fallback = join(folder, DEFAULT_PROJECT_SUBDIR);
  if (!existsSync(folder)) return { folder, projectDir: fallback, realDir: fallback, unavailable: `the folder ${folder} is missing` };
  const mk = readMarker(folder);
  if (!mk.ok) return { folder, projectDir: fallback, realDir: fallback, unavailable: mk.message };
  if (mk.marker.projectId !== projectId) {
    return { folder, projectDir: fallback, realDir: fallback, unavailable: `${MARKER_FILE} in ${folder} now names project "${mk.marker.projectId}", not "${projectId}"` };
  }
  const projectDir = join(folder, mk.marker.projectDir);
  let realDir = projectDir;
  try {
    if (!statSync(projectDir).isDirectory()) return { folder, projectDir, realDir, unavailable: `${projectDir} is not a folder` };
    realDir = realpathSync(projectDir);
  } catch {
    return { folder, projectDir, realDir, unavailable: `the project folder ${projectDir} is missing` };
  }
  return { folder, projectDir, realDir };
}

/** Load `<root>/registry.json` (absent ⇒ empty). Entries whose folder is gone are kept, flagged unavailable. */
export function loadRegistry(root: string): Map<string, RegisteredProject> {
  const out = new Map<string, RegisteredProject>();
  let doc: unknown;
  try {
    doc = JSON.parse(readFileSync(join(root, REGISTRY_FILE), 'utf8'));
  } catch {
    return out;
  }
  const projects = (doc as { projects?: Record<string, { folder?: unknown }> }).projects ?? {};
  for (const [id, rec] of Object.entries(projects)) {
    if (!ID_RE.test(id) || typeof rec?.folder !== 'string' || !isAbsolute(rec.folder)) continue;
    out.set(id, resolveEntry(normalize(rec.folder), id));
  }
  return out;
}

export function saveRegistry(root: string, registry: ReadonlyMap<string, RegisteredProject>): void {
  const projects: Record<string, { folder: string }> = {};
  for (const id of [...registry.keys()].sort()) projects[id] = { folder: registry.get(id)!.folder };
  writeSmallFileAtomic(join(root, REGISTRY_FILE), new TextEncoder().encode(`${JSON.stringify({ registryVersion: 1, projects }, null, 2)}\n`));
}

/** Walk up from `start` to the nearest folder holding a marker. */
export function findMarkerFolder(start: string): string | null {
  let dir = normalize(start);
  for (;;) {
    if (existsSync(join(dir, MARKER_FILE))) return dir;
    const up = dirname(dir);
    if (up === dir) return null;
    dir = up;
  }
}
