/**
 * Generated levels of detail at the command boundary: a model version
 * converted with levels keeps `convertedFrom.lods` in canonical form; the
 * model refuses shares that are not decreasing and in (0, 1) and levels on a
 * file that is not a GLB; `generateLods: true` reaching the command layer
 * (no host made the levels) is refused, `false` is accepted; `importAssets`
 * takes the setting for the host that prepares its files.
 */
import { describe, expect, it } from 'vitest';
import { MESH_LOD_RATIOS_DEFAULT } from '@thirdlight/project-model/limits';
import type { SceneV4 } from '@thirdlight/project-model';

import { applyMutation, createCommandState } from './index';
import type { CommandState, ContentDocument } from './index';
import { validateImportAssetsArgs } from './import-assets';
import { m2EnvelopeV4 } from './test-fixtures';

const BEFORE = m2EnvelopeV4('contracts/commands/prefab-scenario.before.json');
type State = CommandState<SceneV4>;
const RECIPE = { profile: 'gltf-glb', recipeVersion: 1, toolchain: { three: '0.186.0' }, extensions: [] };
const METRICS = { nodes: 4, meshes: 4, primitives: 4, materials: 0, images: 0, textures: 0, vertices: 1000, triangles: 3500, animations: 0, animationChannels: 0, clipDurationMs: 0, decodedGeometryBytes: 40000, decodedImageBytes: 0 };
const CONVERTED = { format: 'glb', sourceDigest: 'b'.repeat(64), sourceByteLength: 9000, sourcePath: 'assets/props/rock.glb', converter: { name: 'texture-extract', version: '1.0' }, lods: [...MESH_LOD_RATIOS_DEFAULT] };

let counter = 0;
function run(op: string, args: Record<string, unknown>): { ok: boolean; state: State; message: string } {
  counter += 1;
  const s = createCommandState(structuredClone(BEFORE.scene), structuredClone(BEFORE.content) as ContentDocument) as unknown as State;
  const out = applyMutation(s, { op, projectId: BEFORE.projectId, expectedRevision: s.scene.revision, requestId: `req-${(0x302a00 + counter).toString(16).padStart(32, '0')}`, args });
  const result = out.result as unknown as { ok: boolean; error?: { message: string; details?: { message: string }[] } };
  return { ok: result.ok, state: ((out as { state?: State }).state ?? s) as State, message: result.error?.details?.[0]?.message ?? result.error?.message ?? '' };
}
const publish = (extra: Record<string, unknown>): Record<string, unknown> => ({ mode: 'create', assetId: 'rock-0001', kind: 'model', sourceDigest: 'a'.repeat(64), sourceByteLength: 12000, importRecipe: RECIPE, metrics: METRICS, importedAt: '2026-10-07T00:00:00Z', ...extra });

describe('generated levels of detail', () => {
  it('a version converted with levels keeps its shares', () => {
    const r = run('publishAsset', publish({ convertedFrom: CONVERTED }));
    expect(r.ok, r.message).toBe(true);
    const rec = (r.state.content as unknown as { assets: { assetId: string; versions: { convertedFrom?: unknown }[] }[] }).assets.find((a) => a.assetId === 'rock-0001')!;
    expect(rec.versions[0]!.convertedFrom).toEqual(CONVERTED);
  });

  it('refuses shares out of order or range, and levels on a file that is not a GLB', () => {
    expect(run('publishAsset', publish({ convertedFrom: { ...CONVERTED, lods: [0.25, 0.5] } })).message).toMatch(/lods lists the triangle share/);
    expect(run('publishAsset', publish({ convertedFrom: { ...CONVERTED, lods: [1] } })).message).toMatch(/lods lists the triangle share/);
    expect(run('publishAsset', publish({ convertedFrom: { ...CONVERTED, lods: [] } })).message).toMatch(/lods lists the triangle share/);
    expect(run('publishAsset', publish({ convertedFrom: { ...CONVERTED, format: 'fbx', converter: { name: 'blender', version: '4.2' } } })).message).toMatch(/not permitted/);
    const { lods: _lods, ...fbx } = CONVERTED;
    expect(run('publishAsset', publish({ convertedFrom: { ...fbx, format: 'fbx', converter: { name: 'blender', version: '4.2' } } })).ok).toBe(true);
  });

  it('generateLods: true is the backend\'s step (refused here), false is accepted; only a model takes it', () => {
    expect(run('publishAsset', publish({ generateLods: true })).message).toMatch(/generated by the backend/);
    expect(run('publishAsset', publish({ generateLods: false })).ok).toBe(true);
    expect(run('publishAsset', publish({ generateLods: 'yes' })).ok).toBe(false);
    expect(run('publishAsset', publish({ kind: 'audio', generateLods: false })).message).toMatch(/only a model/);
  });

  it('importAssets takes generateLods for the host that prepares the files', () => {
    expect(validateImportAssetsArgs({ folder: 'assets/rocks', generateLods: true })).toEqual({ ok: true, args: { folder: 'assets/rocks', generateLods: true } });
    expect(validateImportAssetsArgs({ folder: 'assets/rocks', generateLods: 1 }).ok).toBe(false);
  });
});
